FROM golang:1.25-bookworm

WORKDIR /app

RUN go install github.com/air-verse/air@latest

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
            poppler-utils \
            unoconv \
            libreoffice-writer \
            fonts-dejavu-core \
            fonts-liberation && \
        rm -rf /var/lib/apt/lists/*

COPY go.mod go.sum . 

RUN go mod download

COPY . .

EXPOSE 8081
CMD ["air", "-c", ".air.worker.toml"]
