CREATE TABLE IF NOT EXISTS stats (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    amount INT NOT NULL DEFAULT 0,
    duration BIGINT NOT NULL DEFAULT 0,
    stat_type TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS project_files
ADD COLUMN IF NOT EXISTS token_count INT NOT NULL DEFAULT 0;
