FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock drizzle.config.ts ./
COPY apps/api/package.json apps/api/package.json
COPY apps/frontend/package.json apps/frontend/package.json
COPY apps/worker/package.json apps/worker/package.json
COPY packages/ai/package.json packages/ai/package.json
COPY packages/auth/package.json packages/auth/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/files/package.json packages/files/package.json
COPY packages/graph/package.json packages/graph/package.json
COPY packages/logger/package.json packages/logger/package.json

RUN bun install --frozen-lockfile

COPY migrations migrations
COPY packages/db/src/tables packages/db/src/tables

CMD ["bunx", "drizzle-kit", "migrate"]
