// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteEntitiesWithoutSources = `-- name: DeleteEntitiesWithoutSources :exec
DELETE FROM entities 
WHERE project_id = $1 
  AND id NOT IN (SELECT DISTINCT entity_id FROM entity_sources)
`

func (q *Queries) DeleteEntitiesWithoutSources(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteEntitiesWithoutSources, projectID)
	return err
}

const deleteProjectEntitiesByIDs = `-- name: DeleteProjectEntitiesByIDs :exec
DELETE FROM entities
WHERE project_id = $1
  AND id = ANY($2::text[])
`

type DeleteProjectEntitiesByIDsParams struct {
	ProjectID string   `json:"project_id"`
	Ids       []string `json:"ids"`
}

func (q *Queries) DeleteProjectEntitiesByIDs(ctx context.Context, arg DeleteProjectEntitiesByIDsParams) error {
	_, err := q.db.Exec(ctx, deleteProjectEntitiesByIDs, arg.ProjectID, arg.Ids)
	return err
}

const findEntitiesWithSimilarNames = `-- name: FindEntitiesWithSimilarNames :many
SELECT e1.id as id1, e1.name as name1, e1.type as type1,
       e2.id as id2, e2.name as name2, e2.type as type2
FROM entities e1
JOIN entities e2 ON e2.project_id = $1
    AND e1.type = e2.type
    AND e2.type NOT IN ('FACT', 'FILE')
    AND e2.name % e1.name
    AND similarity(e1.name, e2.name) > 0.5
WHERE e1.id < e2.id AND e1.project_id = $1 AND e1.type NOT IN ('FACT', 'FILE')
`

type FindEntitiesWithSimilarNamesRow struct {
	Id1   string `json:"id1"`
	Name1 string `json:"name1"`
	Type1 string `json:"type1"`
	Id2   string `json:"id2"`
	Name2 string `json:"name2"`
	Type2 string `json:"type2"`
}

func (q *Queries) FindEntitiesWithSimilarNames(ctx context.Context, projectID string) ([]FindEntitiesWithSimilarNamesRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesWithSimilarNames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEntitiesWithSimilarNamesRow{}
	for rows.Next() {
		var i FindEntitiesWithSimilarNamesRow
		if err := rows.Scan(
			&i.Id1,
			&i.Name1,
			&i.Type1,
			&i.Id2,
			&i.Name2,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntitiesWithSimilarNamesForEntityIDs = `-- name: FindEntitiesWithSimilarNamesForEntityIDs :many
WITH seed AS (
    SELECT e.id, e.name, e.type
    FROM entities e
    WHERE e.project_id = $1
      AND e.id = ANY($2::text[])
      AND e.type NOT IN ('FACT', 'FILE')
)
SELECT DISTINCT ON (
    LEAST(seed.id, candidate.id),
    GREATEST(seed.id, candidate.id)
)
    LEAST(seed.id, candidate.id)::text as id1,
    (CASE WHEN seed.id < candidate.id THEN seed.name ELSE candidate.name END)::text as name1,
    (CASE WHEN seed.id < candidate.id THEN seed.type ELSE candidate.type END)::text as type1,
    GREATEST(seed.id, candidate.id)::text as id2,
    (CASE WHEN seed.id < candidate.id THEN candidate.name ELSE seed.name END)::text as name2,
    (CASE WHEN seed.id < candidate.id THEN candidate.type ELSE seed.type END)::text as type2
FROM seed
JOIN entities candidate ON candidate.project_id = $1
    AND candidate.type = seed.type
    AND candidate.type NOT IN ('FACT', 'FILE')
    AND candidate.id <> seed.id
    AND candidate.name % seed.name
    AND similarity(candidate.name, seed.name) > 0.5
ORDER BY LEAST(seed.id, candidate.id), GREATEST(seed.id, candidate.id)
`

type FindEntitiesWithSimilarNamesForEntityIDsParams struct {
	ProjectID string   `json:"project_id"`
	EntityIds []string `json:"entity_ids"`
}

type FindEntitiesWithSimilarNamesForEntityIDsRow struct {
	Id1   string `json:"id1"`
	Name1 string `json:"name1"`
	Type1 string `json:"type1"`
	Id2   string `json:"id2"`
	Name2 string `json:"name2"`
	Type2 string `json:"type2"`
}

func (q *Queries) FindEntitiesWithSimilarNamesForEntityIDs(ctx context.Context, arg FindEntitiesWithSimilarNamesForEntityIDsParams) ([]FindEntitiesWithSimilarNamesForEntityIDsRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesWithSimilarNamesForEntityIDs, arg.ProjectID, arg.EntityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEntitiesWithSimilarNamesForEntityIDsRow{}
	for rows.Next() {
		var i FindEntitiesWithSimilarNamesForEntityIDsRow
		if err := rows.Scan(
			&i.Id1,
			&i.Name1,
			&i.Type1,
			&i.Id2,
			&i.Name2,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesWithSourcesFromFiles = `-- name: GetEntitiesWithSourcesFromFiles :many
SELECT DISTINCT e.id, e.name, e.type, e.description
FROM entities e
JOIN entity_sources es ON es.entity_id = e.id
JOIN text_units tu ON tu.id = es.text_unit_id
WHERE tu.project_file_id = ANY($1::text[])
  AND e.project_id = $2
`

type GetEntitiesWithSourcesFromFilesParams struct {
	Column1   []string `json:"column_1"`
	ProjectID string   `json:"project_id"`
}

type GetEntitiesWithSourcesFromFilesRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

func (q *Queries) GetEntitiesWithSourcesFromFiles(ctx context.Context, arg GetEntitiesWithSourcesFromFilesParams) ([]GetEntitiesWithSourcesFromFilesRow, error) {
	rows, err := q.db.Query(ctx, getEntitiesWithSourcesFromFiles, arg.Column1, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntitiesWithSourcesFromFilesRow{}
	for rows.Next() {
		var i GetEntitiesWithSourcesFromFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesWithSourcesFromUnits = `-- name: GetEntitiesWithSourcesFromUnits :many
SELECT DISTINCT e.id, e.name, e.type, e.description
FROM entities e
JOIN entity_sources es ON es.entity_id = e.id
WHERE es.text_unit_id = ANY($1::text[])
  AND e.project_id = $2
`

type GetEntitiesWithSourcesFromUnitsParams struct {
	Column1   []string `json:"column_1"`
	ProjectID string   `json:"project_id"`
}

type GetEntitiesWithSourcesFromUnitsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

func (q *Queries) GetEntitiesWithSourcesFromUnits(ctx context.Context, arg GetEntitiesWithSourcesFromUnitsParams) ([]GetEntitiesWithSourcesFromUnitsRow, error) {
	rows, err := q.db.Query(ctx, getEntitiesWithSourcesFromUnits, arg.Column1, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntitiesWithSourcesFromUnitsRow{}
	for rows.Next() {
		var i GetEntitiesWithSourcesFromUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitySourceCountsByIDs = `-- name: GetEntitySourceCountsByIDs :many
SELECT e.id, COUNT(es.id)::int AS source_count
FROM entities e
LEFT JOIN entity_sources es ON es.entity_id = e.id
WHERE e.id = ANY($1::text[])
  AND e.project_id = $2
GROUP BY e.id
`

type GetEntitySourceCountsByIDsParams struct {
	Column1   []string `json:"column_1"`
	ProjectID string   `json:"project_id"`
}

type GetEntitySourceCountsByIDsRow struct {
	ID          string `json:"id"`
	SourceCount int32  `json:"source_count"`
}

func (q *Queries) GetEntitySourceCountsByIDs(ctx context.Context, arg GetEntitySourceCountsByIDsParams) ([]GetEntitySourceCountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getEntitySourceCountsByIDs, arg.Column1, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntitySourceCountsByIDsRow{}
	for rows.Next() {
		var i GetEntitySourceCountsByIDsRow
		if err := rows.Scan(&i.ID, &i.SourceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitySourceDescriptionsBatch = `-- name: GetEntitySourceDescriptionsBatch :many
SELECT es.id, es.created_at, es.description
FROM entity_sources es
WHERE es.entity_id = $1
  AND (
      es.created_at > $2
      OR (es.created_at = $2 AND es.id > $3)
  )
ORDER BY es.created_at, es.id
LIMIT $4
`

type GetEntitySourceDescriptionsBatchParams struct {
	EntityID        string             `json:"entity_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	BatchLimit      int32              `json:"batch_limit"`
}

type GetEntitySourceDescriptionsBatchRow struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description string             `json:"description"`
}

func (q *Queries) GetEntitySourceDescriptionsBatch(ctx context.Context, arg GetEntitySourceDescriptionsBatchParams) ([]GetEntitySourceDescriptionsBatchRow, error) {
	rows, err := q.db.Query(ctx, getEntitySourceDescriptionsBatch,
		arg.EntityID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntitySourceDescriptionsBatchRow{}
	for rows.Next() {
		var i GetEntitySourceDescriptionsBatchRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitySourceDescriptionsForFilesBatch = `-- name: GetEntitySourceDescriptionsForFilesBatch :many
SELECT es.id, es.created_at, es.description
FROM entity_sources es
JOIN text_units tu ON tu.id = es.text_unit_id
WHERE es.entity_id = $1
  AND tu.project_file_id = ANY($2::text[])
  AND (
      es.created_at > $3
      OR (es.created_at = $3 AND es.id > $4)
  )
ORDER BY es.created_at, es.id
LIMIT $5
`

type GetEntitySourceDescriptionsForFilesBatchParams struct {
	EntityID        string             `json:"entity_id"`
	FileIds         []string           `json:"file_ids"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	BatchLimit      int32              `json:"batch_limit"`
}

type GetEntitySourceDescriptionsForFilesBatchRow struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description string             `json:"description"`
}

func (q *Queries) GetEntitySourceDescriptionsForFilesBatch(ctx context.Context, arg GetEntitySourceDescriptionsForFilesBatchParams) ([]GetEntitySourceDescriptionsForFilesBatchRow, error) {
	rows, err := q.db.Query(ctx, getEntitySourceDescriptionsForFilesBatch,
		arg.EntityID,
		arg.FileIds,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntitySourceDescriptionsForFilesBatchRow{}
	for rows.Next() {
		var i GetEntitySourceDescriptionsForFilesBatchRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityTypes = `-- name: GetEntityTypes :many
SELECT e.type, COUNT(*) as count
FROM entities e
WHERE e.project_id = $1
GROUP BY e.type
ORDER BY count DESC
`

type GetEntityTypesRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (q *Queries) GetEntityTypes(ctx context.Context, projectID string) ([]GetEntityTypesRow, error) {
	rows, err := q.db.Query(ctx, getEntityTypes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntityTypesRow{}
	for rows.Next() {
		var i GetEntityTypesRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectEntities = `-- name: GetProjectEntities :many
SELECT e.id, e.name, e.description, e.type FROM entities e WHERE e.project_id = $1
`

type GetProjectEntitiesRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

func (q *Queries) GetProjectEntities(ctx context.Context, projectID string) ([]GetProjectEntitiesRow, error) {
	rows, err := q.db.Query(ctx, getProjectEntities, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectEntitiesRow{}
	for rows.Next() {
		var i GetProjectEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectEntitiesByIDs = `-- name: GetProjectEntitiesByIDs :many
SELECT e.id, e.name, e.description, e.type FROM entities e WHERE e.id = ANY($1::text[])
`

type GetProjectEntitiesByIDsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

func (q *Queries) GetProjectEntitiesByIDs(ctx context.Context, dollar_1 []string) ([]GetProjectEntitiesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProjectEntitiesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectEntitiesByIDsRow{}
	for rows.Next() {
		var i GetProjectEntitiesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectEntitiesByIDsForUpdate = `-- name: GetProjectEntitiesByIDsForUpdate :many
SELECT e.id, e.name, e.description, e.type
FROM entities e
WHERE e.project_id = $1
  AND e.id = ANY($2::text[])
ORDER BY e.id
FOR UPDATE
`

type GetProjectEntitiesByIDsForUpdateParams struct {
	ProjectID string   `json:"project_id"`
	Ids       []string `json:"ids"`
}

type GetProjectEntitiesByIDsForUpdateRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

func (q *Queries) GetProjectEntitiesByIDsForUpdate(ctx context.Context, arg GetProjectEntitiesByIDsForUpdateParams) ([]GetProjectEntitiesByIDsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getProjectEntitiesByIDsForUpdate, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectEntitiesByIDsForUpdateRow{}
	for rows.Next() {
		var i GetProjectEntitiesByIDsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectEntitiesByNames = `-- name: GetProjectEntitiesByNames :many
SELECT e.id, e.name, e.description, e.type FROM entities e WHERE e.project_id = $1 AND e.name = ANY($2::text[])
`

type GetProjectEntitiesByNamesParams struct {
	ProjectID string   `json:"project_id"`
	Column2   []string `json:"column_2"`
}

type GetProjectEntitiesByNamesRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

func (q *Queries) GetProjectEntitiesByNames(ctx context.Context, arg GetProjectEntitiesByNamesParams) ([]GetProjectEntitiesByNamesRow, error) {
	rows, err := q.db.Query(ctx, getProjectEntitiesByNames, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectEntitiesByNamesRow{}
	for rows.Next() {
		var i GetProjectEntitiesByNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectEntitiesWithSourceCountsByIDs = `-- name: GetProjectEntitiesWithSourceCountsByIDs :many
SELECT e.id, e.name, e.description, e.type,
       COUNT(es.id)::bigint AS source_count
FROM entities e
LEFT JOIN entity_sources es ON es.entity_id = e.id
WHERE e.project_id = $1
  AND e.id = ANY($2::text[])
GROUP BY e.id, e.name, e.description, e.type
`

type GetProjectEntitiesWithSourceCountsByIDsParams struct {
	ProjectID string   `json:"project_id"`
	Ids       []string `json:"ids"`
}

type GetProjectEntitiesWithSourceCountsByIDsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
	SourceCount int64  `json:"source_count"`
}

func (q *Queries) GetProjectEntitiesWithSourceCountsByIDs(ctx context.Context, arg GetProjectEntitiesWithSourceCountsByIDsParams) ([]GetProjectEntitiesWithSourceCountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProjectEntitiesWithSourceCountsByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectEntitiesWithSourceCountsByIDsRow{}
	for rows.Next() {
		var i GetProjectEntitiesWithSourceCountsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.SourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectEntityByID = `-- name: GetProjectEntityByID :one
SELECT e.id, e.name, e.description, e.type FROM entities e WHERE e.id = $1
`

type GetProjectEntityByIDRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

func (q *Queries) GetProjectEntityByID(ctx context.Context, id string) (GetProjectEntityByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectEntityByID, id)
	var i GetProjectEntityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
	)
	return i, err
}

const getProjectEntityNames = `-- name: GetProjectEntityNames :many
SELECT DISTINCT e.name FROM entities e WHERE e.project_id = $1
`

func (q *Queries) GetProjectEntityNames(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getProjectEntityNames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferEntitySourcesBatch = `-- name: TransferEntitySourcesBatch :exec
UPDATE entity_sources es
SET entity_id = $1
FROM entities e
WHERE es.entity_id = e.id
  AND e.project_id = $2
  AND es.entity_id = ANY($3::text[])
`

type TransferEntitySourcesBatchParams struct {
	CanonicalID string   `json:"canonical_id"`
	ProjectID   string   `json:"project_id"`
	EntityIds   []string `json:"entity_ids"`
}

func (q *Queries) TransferEntitySourcesBatch(ctx context.Context, arg TransferEntitySourcesBatchParams) error {
	_, err := q.db.Exec(ctx, transferEntitySourcesBatch, arg.CanonicalID, arg.ProjectID, arg.EntityIds)
	return err
}

const updateEntityName = `-- name: UpdateEntityName :exec
UPDATE entities
SET name = $1, updated_at = NOW()
WHERE id = $2
  AND project_id = $3
`

type UpdateEntityNameParams struct {
	Name      string `json:"name"`
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) UpdateEntityName(ctx context.Context, arg UpdateEntityNameParams) error {
	_, err := q.db.Exec(ctx, updateEntityName, arg.Name, arg.ID, arg.ProjectID)
	return err
}

const updateProjectEntitiesByIDs = `-- name: UpdateProjectEntitiesByIDs :exec
WITH input AS (
    SELECT
        u.id,
        ($1::text[])[u.ord]::text AS description,
        ($2::vector[])[u.ord]::vector AS embedding
    FROM unnest($3::text[]) WITH ORDINALITY AS u(id, ord)
)
UPDATE entities e
SET description = input.description,
    embedding = input.embedding,
    updated_at = NOW()
FROM input
WHERE e.id = input.id
`

type UpdateProjectEntitiesByIDsParams struct {
	Descriptions []string          `json:"descriptions"`
	Embeddings   []pgvector.Vector `json:"embeddings"`
	Ids          []string          `json:"ids"`
}

func (q *Queries) UpdateProjectEntitiesByIDs(ctx context.Context, arg UpdateProjectEntitiesByIDsParams) error {
	_, err := q.db.Exec(ctx, updateProjectEntitiesByIDs, arg.Descriptions, arg.Embeddings, arg.Ids)
	return err
}

const updateProjectEntity = `-- name: UpdateProjectEntity :one
UPDATE entities SET description = $2, embedding = $3, updated_at = NOW() WHERE id = $1 RETURNING id
`

type UpdateProjectEntityParams struct {
	ID          string          `json:"id"`
	Description string          `json:"description"`
	Embedding   pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateProjectEntity(ctx context.Context, arg UpdateProjectEntityParams) (string, error) {
	row := q.db.QueryRow(ctx, updateProjectEntity, arg.ID, arg.Description, arg.Embedding)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertEntitySources = `-- name: UpsertEntitySources :exec
WITH input AS (
    SELECT
        u.id,
        ($1::text[])[u.ord]::text AS entity_id,
        ($2::text[])[u.ord]::text AS text_unit_id,
        ($3::text[])[u.ord]::text AS description,
        ($4::vector[])[u.ord]::vector AS embedding
    FROM unnest($5::text[]) WITH ORDINALITY AS u(id, ord)
)
INSERT INTO entity_sources (id, entity_id, text_unit_id, description, embedding)
SELECT id, entity_id, text_unit_id, description, embedding
FROM input
ON CONFLICT (id) DO UPDATE
SET entity_id = EXCLUDED.entity_id,
    text_unit_id = EXCLUDED.text_unit_id,
    description = EXCLUDED.description,
    embedding = EXCLUDED.embedding,
    updated_at = NOW()
`

type UpsertEntitySourcesParams struct {
	EntityIds    []string          `json:"entity_ids"`
	TextUnitIds  []string          `json:"text_unit_ids"`
	Descriptions []string          `json:"descriptions"`
	Embeddings   []pgvector.Vector `json:"embeddings"`
	Ids          []string          `json:"ids"`
}

func (q *Queries) UpsertEntitySources(ctx context.Context, arg UpsertEntitySourcesParams) error {
	_, err := q.db.Exec(ctx, upsertEntitySources,
		arg.EntityIds,
		arg.TextUnitIds,
		arg.Descriptions,
		arg.Embeddings,
		arg.Ids,
	)
	return err
}

const upsertProjectEntities = `-- name: UpsertProjectEntities :many
WITH input AS (
    SELECT
        u.id,
        ($2::text[])[u.ord]::text AS name,
        ($3::text[])[u.ord]::text AS description,
        ($4::text[])[u.ord]::text AS type,
        ($5::vector[])[u.ord]::vector AS embedding
    FROM unnest($6::text[]) WITH ORDINALITY AS u(id, ord)
)
INSERT INTO entities (id, project_id, name, description, type, embedding)
SELECT id, $1::text, name, description, type, embedding
FROM input
ON CONFLICT (id) DO UPDATE
SET project_id = EXCLUDED.project_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    type = EXCLUDED.type,
    embedding = EXCLUDED.embedding,
    updated_at = NOW()
RETURNING id
`

type UpsertProjectEntitiesParams struct {
	ProjectID    string            `json:"project_id"`
	Names        []string          `json:"names"`
	Descriptions []string          `json:"descriptions"`
	Types        []string          `json:"types"`
	Embeddings   []pgvector.Vector `json:"embeddings"`
	Ids          []string          `json:"ids"`
}

func (q *Queries) UpsertProjectEntities(ctx context.Context, arg UpsertProjectEntitiesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, upsertProjectEntities,
		arg.ProjectID,
		arg.Names,
		arg.Descriptions,
		arg.Types,
		arg.Embeddings,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
