// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package pgdb

import (
	"context"
)

const addUserToGroup = `-- name: AddUserToGroup :one
INSERT INTO group_users (group_id, user_id, role)
VALUES ($1, $2, $3) RETURNING group_id, user_id, role, created_at, updated_at
`

type AddUserToGroupParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
	Role    string `json:"role"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (GroupUser, error) {
	row := q.db.QueryRow(ctx, addUserToGroup, arg.GroupID, arg.UserID, arg.Role)
	var i GroupUser
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name)
VALUES ($1, $2) RETURNING id, name
`

type CreateGroupParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.ID, arg.Name)
	var i Group
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteUserFromGroup = `-- name: DeleteUserFromGroup :exec
DELETE FROM group_users WHERE group_id = $1 AND user_id = $2
`

type DeleteUserFromGroupParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) DeleteUserFromGroup(ctx context.Context, arg DeleteUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, deleteUserFromGroup, arg.GroupID, arg.UserID)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT
    g.id AS group_id, 
    g.name AS group_name,
    'admin'::TEXT AS role
FROM groups g
ORDER BY g.id
`

type GetAllGroupsRow struct {
	GroupID   string `json:"group_id"`
	GroupName string `json:"group_name"`
	Role      string `json:"role"`
}

func (q *Queries) GetAllGroups(ctx context.Context) ([]GetAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllGroupsRow{}
	for rows.Next() {
		var i GetAllGroupsRow
		if err := rows.Scan(&i.GroupID, &i.GroupName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, name FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGroupUsers = `-- name: GetGroupUsers :many
SELECT group_id, user_id, role, created_at, updated_at FROM group_users WHERE group_id = $1
`

func (q *Queries) GetGroupUsers(ctx context.Context, groupID string) ([]GroupUser, error) {
	rows, err := q.db.Query(ctx, getGroupUsers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupUser{}
	for rows.Next() {
		var i GroupUser
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsForUser = `-- name: GetGroupsForUser :many
SELECT
    g.id AS group_id, 
    g.name AS group_name,
    gu.role AS role
FROM groups g
JOIN group_users gu
    ON gu.group_id = g.id
WHERE gu.user_id = $1
`

type GetGroupsForUserRow struct {
	GroupID   string `json:"group_id"`
	GroupName string `json:"group_name"`
	Role      string `json:"role"`
}

func (q *Queries) GetGroupsForUser(ctx context.Context, userID string) ([]GetGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, getGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupsForUserRow{}
	for rows.Next() {
		var i GetGroupsForUserRow
		if err := rows.Scan(&i.GroupID, &i.GroupName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInGroup = `-- name: IsUserInGroup :one
SELECT COUNT(*) AS count FROM group_users WHERE group_id = $1 AND user_id = $2
`

type IsUserInGroupParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, isUserInGroup, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET name = $2 WHERE id = $1 RETURNING id, name
`

type UpdateGroupParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name)
	var i Group
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
