// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Account struct {
	ID                    int64              `json:"id"`
	UserId                int64              `json:"user_id"`
	AccountId             string             `json:"account_id"`
	ProviderId            string             `json:"provider_id"`
	AccessToken           pgtype.Text        `json:"access_token"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text        `json:"scope"`
	IdToken               pgtype.Text        `json:"id_token"`
	Password              pgtype.Text        `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ChatMessage struct {
	ID            int64              `json:"id"`
	ChatID        int64              `json:"chat_id"`
	Role          string             `json:"role"`
	Content       string             `json:"content"`
	ToolCallID    string             `json:"tool_call_id"`
	ToolName      string             `json:"tool_name"`
	ToolArguments string             `json:"tool_arguments"`
	ToolExecution string             `json:"tool_execution"`
	Reasoning     pgtype.Text        `json:"reasoning"`
	Metrics       []byte             `json:"metrics"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Entity struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	ProjectID   int64              `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Type        string             `json:"type"`
	Embedding   pgvector.Vector    `json:"embedding"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EntitySource struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	EntityID    int64              `json:"entity_id"`
	TextUnitID  int64              `json:"text_unit_id"`
	Description string             `json:"description"`
	Embedding   pgvector.Vector    `json:"embedding"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ExtractionStaging struct {
	ID            int64              `json:"id"`
	CorrelationID string             `json:"correlation_id"`
	BatchID       int32              `json:"batch_id"`
	ProjectID     int64              `json:"project_id"`
	DataType      string             `json:"data_type"`
	Data          []byte             `json:"data"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type GroupUser struct {
	GroupID   int64              `json:"group_id"`
	UserID    int64              `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Jwk struct {
	ID         string             `json:"id"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type Project struct {
	ID        int64              `json:"id"`
	GroupID   int64              `json:"group_id"`
	Name      string             `json:"name"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectBatchStatus struct {
	ID                int64              `json:"id"`
	ProjectID         int64              `json:"project_id"`
	CorrelationID     string             `json:"correlation_id"`
	BatchID           int32              `json:"batch_id"`
	TotalBatches      int32              `json:"total_batches"`
	FilesCount        int32              `json:"files_count"`
	FileIds           []int64            `json:"file_ids"`
	Status            string             `json:"status"`
	Operation         string             `json:"operation"`
	EstimatedDuration int64              `json:"estimated_duration"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
}

type ProjectDescriptionJobStatus struct {
	ID              int64              `json:"id"`
	ProjectID       int64              `json:"project_id"`
	CorrelationID   string             `json:"correlation_id"`
	JobID           int32              `json:"job_id"`
	TotalJobs       int32              `json:"total_jobs"`
	EntityIds       []int64            `json:"entity_ids"`
	RelationshipIds []int64            `json:"relationship_ids"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
}

type ProjectFile struct {
	ID         int64              `json:"id"`
	ProjectID  int64              `json:"project_id"`
	Name       string             `json:"name"`
	FileKey    string             `json:"file_key"`
	Deleted    pgtype.Bool        `json:"deleted"`
	TokenCount int32              `json:"token_count"`
	Metadata   pgtype.Text        `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProjectSystemPrompt struct {
	ID        int64              `json:"id"`
	ProjectID int64              `json:"project_id"`
	Prompt    string             `json:"prompt"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectUpdate struct {
	ID            int64              `json:"id"`
	ProjectID     int64              `json:"project_id"`
	UpdateType    string             `json:"update_type"`
	UpdateMessage []byte             `json:"update_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Relationship struct {
	ID          int64              `json:"id"`
	PublicID    string             `json:"public_id"`
	SourceID    int64              `json:"source_id"`
	TargetID    int64              `json:"target_id"`
	ProjectID   int64              `json:"project_id"`
	Rank        float64            `json:"rank"`
	Description string             `json:"description"`
	Embedding   pgvector.Vector    `json:"embedding"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RelationshipSource struct {
	ID             int64              `json:"id"`
	PublicID       string             `json:"public_id"`
	RelationshipID int64              `json:"relationship_id"`
	TextUnitID     int64              `json:"text_unit_id"`
	Description    string             `json:"description"`
	Embedding      pgvector.Vector    `json:"embedding"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID             int64              `json:"id"`
	UserId         int64              `json:"user_id"`
	Token          string             `json:"token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	IpAddress      pgtype.Text        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImpersonatedBy pgtype.Int8        `json:"impersonated_by"`
}

type Stat struct {
	ID        int64              `json:"id"`
	ProjectID int64              `json:"project_id"`
	Amount    int32              `json:"amount"`
	Duration  int64              `json:"duration"`
	StatType  string             `json:"stat_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TextUnit struct {
	ID            int64              `json:"id"`
	PublicID      string             `json:"public_id"`
	ProjectFileID int64              `json:"project_file_id"`
	Text          string             `json:"text"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Role          pgtype.Text        `json:"role"`
	Banned        pgtype.Bool        `json:"banned"`
	BanReason     pgtype.Text        `json:"ban_reason"`
	BanExpires    pgtype.Timestamptz `json:"ban_expires"`
}

type UserChat struct {
	ID        int64              `json:"id"`
	PublicID  string             `json:"public_id"`
	UserID    int64              `json:"user_id"`
	ProjectID pgtype.Int8        `json:"project_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Verification struct {
	ID         int64              `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
