// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Account struct {
	ID                    string             `json:"id"`
	UserId                string             `json:"user_id"`
	AccountId             string             `json:"account_id"`
	ProviderId            string             `json:"provider_id"`
	AccessToken           pgtype.Text        `json:"access_token"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text        `json:"scope"`
	IdToken               pgtype.Text        `json:"id_token"`
	Password              pgtype.Text        `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ChatMessage struct {
	ID            string             `json:"id"`
	ChatID        string             `json:"chat_id"`
	Role          string             `json:"role"`
	Content       string             `json:"content"`
	ToolCallID    string             `json:"tool_call_id"`
	ToolName      string             `json:"tool_name"`
	ToolArguments string             `json:"tool_arguments"`
	ToolExecution string             `json:"tool_execution"`
	Reasoning     pgtype.Text        `json:"reasoning"`
	Metrics       []byte             `json:"metrics"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Entity struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Type        string             `json:"type"`
	Embedding   pgvector.Vector    `json:"embedding"`
	SearchTsv   interface{}        `json:"search_tsv"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EntitySource struct {
	ID          string             `json:"id"`
	EntityID    string             `json:"entity_id"`
	TextUnitID  string             `json:"text_unit_id"`
	Description string             `json:"description"`
	Embedding   pgvector.Vector    `json:"embedding"`
	SearchTsv   interface{}        `json:"search_tsv"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Graph struct {
	ID          string             `json:"id"`
	GroupID     pgtype.Text        `json:"group_id"`
	UserID      pgtype.Text        `json:"user_id"`
	GraphID     pgtype.Text        `json:"graph_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	State       string             `json:"state"`
	Type        pgtype.Text        `json:"type"`
	Hidden      bool               `json:"hidden"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type GroupUser struct {
	GroupID   string             `json:"group_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Jwk struct {
	ID         string             `json:"id"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type ProjectFile struct {
	ID         string             `json:"id"`
	ProjectID  string             `json:"project_id"`
	Name       string             `json:"name"`
	FileKey    string             `json:"file_key"`
	Deleted    pgtype.Bool        `json:"deleted"`
	TokenCount int32              `json:"token_count"`
	Metadata   pgtype.Text        `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProjectSystemPrompt struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"project_id"`
	Prompt    string             `json:"prompt"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectUpdate struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"project_id"`
	UpdateType    string             `json:"update_type"`
	UpdateMessage []byte             `json:"update_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Relationship struct {
	ID          string             `json:"id"`
	SourceID    string             `json:"source_id"`
	TargetID    string             `json:"target_id"`
	ProjectID   string             `json:"project_id"`
	Rank        float64            `json:"rank"`
	Description string             `json:"description"`
	Embedding   pgvector.Vector    `json:"embedding"`
	SearchTsv   interface{}        `json:"search_tsv"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RelationshipSource struct {
	ID             string             `json:"id"`
	RelationshipID string             `json:"relationship_id"`
	TextUnitID     string             `json:"text_unit_id"`
	Description    string             `json:"description"`
	Embedding      pgvector.Vector    `json:"embedding"`
	SearchTsv      interface{}        `json:"search_tsv"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID             string             `json:"id"`
	UserId         string             `json:"user_id"`
	Token          string             `json:"token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	IpAddress      pgtype.Text        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImpersonatedBy pgtype.Text        `json:"impersonated_by"`
}

type Stat struct {
	ID        string             `json:"id"`
	RunID     pgtype.Text        `json:"run_id"`
	Type      string             `json:"type"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StatsWorkflowStepSamplesV struct {
	ID                string             `json:"id"`
	Type              string             `json:"type"`
	RunID             pgtype.Text        `json:"run_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	WorkflowName      interface{}        `json:"workflow_name"`
	WorkflowVersion   interface{}        `json:"workflow_version"`
	Operation         interface{}        `json:"operation"`
	AiAdapter         interface{}        `json:"ai_adapter"`
	ChatModel         interface{}        `json:"chat_model"`
	EmbedModel        interface{}        `json:"embed_model"`
	FileType          interface{}        `json:"file_type"`
	NeedsOcr          interface{}        `json:"needs_ocr"`
	EstimatedTokens   interface{}        `json:"estimated_tokens"`
	ChunkCount        interface{}        `json:"chunk_count"`
	EntityCount       interface{}        `json:"entity_count"`
	RelationshipCount interface{}        `json:"relationship_count"`
	SourceCount       interface{}        `json:"source_count"`
	DurationMs        interface{}        `json:"duration_ms"`
	StepName          string             `json:"step_name"`
	TokenBucket       interface{}        `json:"token_bucket"`
	ChunkBucket       interface{}        `json:"chunk_bucket"`
	SourceBucket      interface{}        `json:"source_bucket"`
}

type TextUnit struct {
	ID            string             `json:"id"`
	ProjectFileID string             `json:"project_file_id"`
	Text          string             `json:"text"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Role          pgtype.Text        `json:"role"`
	Banned        pgtype.Bool        `json:"banned"`
	BanReason     pgtype.Text        `json:"ban_reason"`
	BanExpires    pgtype.Timestamptz `json:"ban_expires"`
}

type UserChat struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ProjectID pgtype.Text        `json:"project_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Verification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowRun struct {
	ID                      string             `json:"id"`
	Name                    string             `json:"name"`
	Version                 string             `json:"version"`
	Input                   []byte             `json:"input"`
	Output                  []byte             `json:"output"`
	Status                  string             `json:"status"`
	ErrorMessage            string             `json:"error_message"`
	AttemptCount            int32              `json:"attempt_count"`
	AvailableAt             pgtype.Timestamptz `json:"available_at"`
	WorkerID                string             `json:"worker_id"`
	LeaseToken              string             `json:"lease_token"`
	WaitReason              string             `json:"wait_reason"`
	SleepUntil              pgtype.Timestamptz `json:"sleep_until"`
	IdempotencyKey          pgtype.Text        `json:"idempotency_key"`
	ParentRunID             pgtype.Text        `json:"parent_run_id"`
	ParentStepName          pgtype.Text        `json:"parent_step_name"`
	RootRunID               pgtype.Text        `json:"root_run_id"`
	RetryInitialIntervalMs  int64              `json:"retry_initial_interval_ms"`
	RetryBackoffCoefficient float64            `json:"retry_backoff_coefficient"`
	RetryMaximumIntervalMs  int64              `json:"retry_maximum_interval_ms"`
	RetryMaximumAttempts    int32              `json:"retry_maximum_attempts"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	LastHeartbeatAt         pgtype.Timestamptz `json:"last_heartbeat_at"`
}

type WorkflowStat struct {
	ID                      string             `json:"id"`
	RunID                   pgtype.Text        `json:"run_id"`
	ProjectID               string             `json:"project_id"`
	CorrelationID           string             `json:"correlation_id"`
	WorkflowName            string             `json:"workflow_name"`
	WorkflowVersion         string             `json:"workflow_version"`
	SubjectType             string             `json:"subject_type"`
	SubjectID               string             `json:"subject_id"`
	FileID                  pgtype.Text        `json:"file_id"`
	Operation               string             `json:"operation"`
	Status                  string             `json:"status"`
	CurrentStep             string             `json:"current_step"`
	CurrentStepStartedAt    pgtype.Timestamptz `json:"current_step_started_at"`
	EstimatedDuration       int64              `json:"estimated_duration"`
	PredictionSampleCount   int32              `json:"prediction_sample_count"`
	PredictionFallbackLevel int32              `json:"prediction_fallback_level"`
	Metrics                 []byte             `json:"metrics"`
	Prediction              []byte             `json:"prediction"`
	ErrorMessage            string             `json:"error_message"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
}

type WorkflowStepAttempt struct {
	ID            string             `json:"id"`
	RunID         string             `json:"run_id"`
	RunAttempt    int32              `json:"run_attempt"`
	StepName      string             `json:"step_name"`
	StepIndex     int32              `json:"step_index"`
	StepType      string             `json:"step_type"`
	Status        string             `json:"status"`
	Input         []byte             `json:"input"`
	Output        []byte             `json:"output"`
	ErrorMessage  string             `json:"error_message"`
	AttemptNumber int32              `json:"attempt_number"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	SleepUntil    pgtype.Timestamptz `json:"sleep_until"`
	ChildRunID    pgtype.Text        `json:"child_run_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}
