// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddChatMessage(ctx context.Context, arg AddChatMessageParams) error
	AddFileToProject(ctx context.Context, arg AddFileToProjectParams) (ProjectFile, error)
	AddProcessTime(ctx context.Context, arg AddProcessTimeParams) error
	AddProjectUpdate(ctx context.Context, arg AddProjectUpdateParams) error
	AddTokenCountToFile(ctx context.Context, arg AddTokenCountToFileParams) error
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (GroupUser, error)
	AreAllBatchesCompleted(ctx context.Context, correlationID string) (bool, error)
	AreAllDescriptionJobsCompleted(ctx context.Context, correlationID string) (bool, error)
	CountEntitySources(ctx context.Context, entityID int64) (int32, error)
	CreateBatchStatus(ctx context.Context, arg CreateBatchStatusParams) (ProjectBatchStatus, error)
	CreateDescriptionJobStatus(ctx context.Context, arg CreateDescriptionJobStatusParams) (ProjectDescriptionJobStatus, error)
	CreateGroup(ctx context.Context, name string) (Group, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Graph, error)
	CreateProjectWithOwner(ctx context.Context, arg CreateProjectWithOwnerParams) (Graph, error)
	CreateUserChat(ctx context.Context, arg CreateUserChatParams) (UserChat, error)
	DeleteEntitiesWithoutSources(ctx context.Context, projectID int64) error
	DeleteGroup(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteProjectEntity(ctx context.Context, id int64) error
	DeleteProjectFile(ctx context.Context, id int64) error
	DeleteProjectRelationship(ctx context.Context, id int64) error
	DeleteRelationshipsWithoutSources(ctx context.Context, projectID int64) error
	DeleteStagedData(ctx context.Context, arg DeleteStagedDataParams) error
	DeleteTextUnitsByFileIDs(ctx context.Context, dollar_1 []int64) error
	DeleteUserChatByPublicIDAndProject(ctx context.Context, arg DeleteUserChatByPublicIDAndProjectParams) (int64, error)
	DeleteUserFromGroup(ctx context.Context, arg DeleteUserFromGroupParams) error
	FindDuplicateRelationships(ctx context.Context, projectID int64) ([]FindDuplicateRelationshipsRow, error)
	FindEntitiesWithSimilarNames(ctx context.Context, projectID int64) ([]FindEntitiesWithSimilarNamesRow, error)
	FindEntitiesWithSimilarNamesForEntityIDs(ctx context.Context, arg FindEntitiesWithSimilarNamesForEntityIDsParams) ([]FindEntitiesWithSimilarNamesForEntityIDsRow, error)
	FindRelevantEntitySources(ctx context.Context, arg FindRelevantEntitySourcesParams) ([]FindRelevantEntitySourcesRow, error)
	FindRelevantRelationSources(ctx context.Context, arg FindRelevantRelationSourcesParams) ([]FindRelevantRelationSourcesRow, error)
	FindRelevantSourcesForEntities(ctx context.Context, arg FindRelevantSourcesForEntitiesParams) ([]FindRelevantSourcesForEntitiesRow, error)
	FindRelevantSourcesForEntitiesWithKeywords(ctx context.Context, arg FindRelevantSourcesForEntitiesWithKeywordsParams) ([]FindRelevantSourcesForEntitiesWithKeywordsRow, error)
	FindRelevantSourcesForRelations(ctx context.Context, arg FindRelevantSourcesForRelationsParams) ([]FindRelevantSourcesForRelationsRow, error)
	FindRelevantSourcesForRelationsWithKeywords(ctx context.Context, arg FindRelevantSourcesForRelationsWithKeywordsParams) ([]FindRelevantSourcesForRelationsWithKeywordsRow, error)
	FindSimilarEntities(ctx context.Context, arg FindSimilarEntitiesParams) ([]int64, error)
	FindSimilarEntitySources(ctx context.Context, arg FindSimilarEntitySourcesParams) ([]FindSimilarEntitySourcesRow, error)
	GetAllGroups(ctx context.Context) ([]GetAllGroupsRow, error)
	GetAllProjectsWithGroups(ctx context.Context) ([]GetAllProjectsWithGroupsRow, error)
	GetAvailableExpertProjects(ctx context.Context, arg GetAvailableExpertProjectsParams) ([]GetAvailableExpertProjectsRow, error)
	GetBatchesByCorrelation(ctx context.Context, correlationID string) ([]ProjectBatchStatus, error)
	GetChatMessagesByChatID(ctx context.Context, chatID int64) ([]ChatMessage, error)
	GetChatMessagesByChatIDWithoutServerToolCalls(ctx context.Context, chatID int64) ([]ChatMessage, error)
	GetDeletedProjectFiles(ctx context.Context, projectID int64) ([]ProjectFile, error)
	GetDescriptionJobsByCorrelation(ctx context.Context, correlationID string) ([]ProjectDescriptionJobStatus, error)
	GetEntitiesWithSourcesFromFiles(ctx context.Context, arg GetEntitiesWithSourcesFromFilesParams) ([]GetEntitiesWithSourcesFromFilesRow, error)
	GetEntitiesWithSourcesFromUnits(ctx context.Context, arg GetEntitiesWithSourcesFromUnitsParams) ([]GetEntitiesWithSourcesFromUnitsRow, error)
	GetEntityIDsByPublicIDs(ctx context.Context, arg GetEntityIDsByPublicIDsParams) ([]GetEntityIDsByPublicIDsRow, error)
	GetEntityNeighboursRanked(ctx context.Context, arg GetEntityNeighboursRankedParams) ([]GetEntityNeighboursRankedRow, error)
	GetEntityNeighboursRankedWithKeywords(ctx context.Context, arg GetEntityNeighboursRankedWithKeywordsParams) ([]GetEntityNeighboursRankedWithKeywordsRow, error)
	GetEntitySourceDescriptionsBatch(ctx context.Context, arg GetEntitySourceDescriptionsBatchParams) ([]GetEntitySourceDescriptionsBatchRow, error)
	GetEntitySourceDescriptionsForFilesBatch(ctx context.Context, arg GetEntitySourceDescriptionsForFilesBatchParams) ([]GetEntitySourceDescriptionsForFilesBatchRow, error)
	GetEntityTypes(ctx context.Context, projectID int64) ([]GetEntityTypesRow, error)
	GetExpertProjectByProjectID(ctx context.Context, id int64) (GetExpertProjectByProjectIDRow, error)
	GetExpertProjects(ctx context.Context) ([]GetExpertProjectsRow, error)
	GetFilesFromTextUnitIDs(ctx context.Context, arg GetFilesFromTextUnitIDsParams) ([]GetFilesFromTextUnitIDsRow, error)
	GetFilesWithMetadataFromTextUnitIDs(ctx context.Context, arg GetFilesWithMetadataFromTextUnitIDsParams) ([]GetFilesWithMetadataFromTextUnitIDsRow, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetGroupUsers(ctx context.Context, groupID int64) ([]GroupUser, error)
	GetGroupsForUser(ctx context.Context, userID int64) ([]GetGroupsForUserRow, error)
	GetLatestBatchStatusForFiles(ctx context.Context, arg GetLatestBatchStatusForFilesParams) ([]GetLatestBatchStatusForFilesRow, error)
	GetLatestCorrelationForProject(ctx context.Context, projectID int64) (string, error)
	GetPendingBatchesForProject(ctx context.Context, projectID int64) ([]ProjectBatchStatus, error)
	GetProjectByID(ctx context.Context, id int64) (Graph, error)
	GetProjectEntities(ctx context.Context, projectID int64) ([]GetProjectEntitiesRow, error)
	GetProjectEntitiesByIDs(ctx context.Context, dollar_1 []int64) ([]GetProjectEntitiesByIDsRow, error)
	GetProjectEntitiesByNames(ctx context.Context, arg GetProjectEntitiesByNamesParams) ([]GetProjectEntitiesByNamesRow, error)
	GetProjectEntityByID(ctx context.Context, id int64) (GetProjectEntityByIDRow, error)
	GetProjectEntityNames(ctx context.Context, projectID int64) ([]string, error)
	GetProjectFileByKey(ctx context.Context, arg GetProjectFileByKeyParams) (ProjectFile, error)
	GetProjectFiles(ctx context.Context, projectID int64) ([]ProjectFile, error)
	GetProjectFilesForBatch(ctx context.Context, dollar_1 []int64) ([]ProjectFile, error)
	GetProjectFullProgress(ctx context.Context, correlationID string) (GetProjectFullProgressRow, error)
	GetProjectIDFromTextUnit(ctx context.Context, publicID string) (int64, error)
	GetProjectIDsForFiles(ctx context.Context, fileIds []int64) ([]int64, error)
	GetProjectRelationships(ctx context.Context, projectID int64) ([]GetProjectRelationshipsRow, error)
	GetProjectRelationshipsWithEntityNamesByIDs(ctx context.Context, ids []int64) ([]GetProjectRelationshipsWithEntityNamesByIDsRow, error)
	GetProjectSystemPrompts(ctx context.Context, projectID int64) ([]ProjectSystemPrompt, error)
	GetProjectsByGroup(ctx context.Context, groupID sql.NullInt64) ([]Graph, error)
	GetProjectsForUser(ctx context.Context, userID int64) ([]GetProjectsForUserRow, error)
	GetRelationshipSourceDescriptionsBatch(ctx context.Context, arg GetRelationshipSourceDescriptionsBatchParams) ([]GetRelationshipSourceDescriptionsBatchRow, error)
	GetRelationshipSourceDescriptionsForFilesBatch(ctx context.Context, arg GetRelationshipSourceDescriptionsForFilesBatchParams) ([]GetRelationshipSourceDescriptionsForFilesBatchRow, error)
	GetRelationshipsByIDs(ctx context.Context, dollar_1 []int64) ([]GetRelationshipsByIDsRow, error)
	GetRelationshipsWithSourcesFromFiles(ctx context.Context, arg GetRelationshipsWithSourcesFromFilesParams) ([]GetRelationshipsWithSourcesFromFilesRow, error)
	GetRelationshipsWithSourcesFromUnits(ctx context.Context, arg GetRelationshipsWithSourcesFromUnitsParams) ([]GetRelationshipsWithSourcesFromUnitsRow, error)
	GetStagedEntities(ctx context.Context, arg GetStagedEntitiesParams) ([][]byte, error)
	GetStagedRelationships(ctx context.Context, arg GetStagedRelationshipsParams) ([][]byte, error)
	GetStagedUnits(ctx context.Context, arg GetStagedUnitsParams) ([][]byte, error)
	GetStaleBatches(ctx context.Context) ([]ProjectBatchStatus, error)
	GetTextUnitByPublicId(ctx context.Context, publicID string) (TextUnit, error)
	GetTextUnitIDsByPublicIDs(ctx context.Context, publicIds []string) ([]GetTextUnitIDsByPublicIDsRow, error)
	GetTextUnitIdsForFiles(ctx context.Context, dollar_1 []int64) ([]GetTextUnitIdsForFilesRow, error)
	GetTokenCountsOfFiles(ctx context.Context, dollar_1 []int64) ([]GetTokenCountsOfFilesRow, error)
	GetUserChatByPublicIDAndProject(ctx context.Context, arg GetUserChatByPublicIDAndProjectParams) (UserChat, error)
	GetUserChatsByProject(ctx context.Context, arg GetUserChatsByProjectParams) ([]GetUserChatsByProjectRow, error)
	GetUserProjects(ctx context.Context, userID sql.NullInt64) ([]GetUserProjectsRow, error)
	InsertStagedDataBatch(ctx context.Context, arg InsertStagedDataBatchParams) error
	IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (int64, error)
	IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (int64, error)
	MarkProjectFileAsDeleted(ctx context.Context, arg MarkProjectFileAsDeletedParams) error
	PredictProjectProcessTime(ctx context.Context, arg PredictProjectProcessTimeParams) (int64, error)
	ResetBatchToPending(ctx context.Context, arg ResetBatchToPendingParams) error
	ResetBatchToPreprocessed(ctx context.Context, arg ResetBatchToPreprocessedParams) error
	ResetDescriptionJobToPending(ctx context.Context, arg ResetDescriptionJobToPendingParams) error
	ResetStaleBatchExtractingToPreprocessed(ctx context.Context, id int64) error
	ResetStaleBatchToPending(ctx context.Context, id int64) error
	ResetStaleBatchToPreprocessed(ctx context.Context, id int64) error
	SearchEntitiesByEmbedding(ctx context.Context, arg SearchEntitiesByEmbeddingParams) ([]SearchEntitiesByEmbeddingRow, error)
	SearchEntitiesByEmbeddingWithKeywords(ctx context.Context, arg SearchEntitiesByEmbeddingWithKeywordsParams) ([]SearchEntitiesByEmbeddingWithKeywordsRow, error)
	SearchEntitiesByType(ctx context.Context, arg SearchEntitiesByTypeParams) ([]SearchEntitiesByTypeRow, error)
	SearchEntitiesByTypeWithKeywords(ctx context.Context, arg SearchEntitiesByTypeWithKeywordsParams) ([]SearchEntitiesByTypeWithKeywordsRow, error)
	SearchRelationshipsByEmbedding(ctx context.Context, arg SearchRelationshipsByEmbeddingParams) ([]SearchRelationshipsByEmbeddingRow, error)
	SearchRelationshipsByEmbeddingWithKeywords(ctx context.Context, arg SearchRelationshipsByEmbeddingWithKeywordsParams) ([]SearchRelationshipsByEmbeddingWithKeywordsRow, error)
	TouchUserChat(ctx context.Context, chatID int64) error
	TransferEntitySources(ctx context.Context, arg TransferEntitySourcesParams) error
	TransferRelationshipSources(ctx context.Context, arg TransferRelationshipSourcesParams) error
	TryStartDescriptionJob(ctx context.Context, arg TryStartDescriptionJobParams) (bool, error)
	TryStartGraphBatch(ctx context.Context, arg TryStartGraphBatchParams) (bool, error)
	TryStartPreprocessBatch(ctx context.Context, arg TryStartPreprocessBatchParams) (bool, error)
	UpdateBatchEstimatedDuration(ctx context.Context, arg UpdateBatchEstimatedDurationParams) error
	UpdateBatchStatus(ctx context.Context, arg UpdateBatchStatusParams) error
	UpdateDescriptionJobStatus(ctx context.Context, arg UpdateDescriptionJobStatusParams) error
	UpdateEntityName(ctx context.Context, arg UpdateEntityNameParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Graph, error)
	UpdateProjectEntitiesByIDs(ctx context.Context, arg UpdateProjectEntitiesByIDsParams) error
	UpdateProjectEntity(ctx context.Context, arg UpdateProjectEntityParams) (int64, error)
	UpdateProjectFileMetadata(ctx context.Context, arg UpdateProjectFileMetadataParams) error
	UpdateProjectRelationship(ctx context.Context, arg UpdateProjectRelationshipParams) (int64, error)
	UpdateProjectRelationshipsByIDs(ctx context.Context, arg UpdateProjectRelationshipsByIDsParams) error
	UpdateProjectState(ctx context.Context, arg UpdateProjectStateParams) (Graph, error)
	UpdateRelationshipRank(ctx context.Context, arg UpdateRelationshipRankParams) error
	UpdateRelationshipSourceEntity(ctx context.Context, arg UpdateRelationshipSourceEntityParams) error
	UpdateRelationshipTargetEntity(ctx context.Context, arg UpdateRelationshipTargetEntityParams) error
	UpsertEntitySources(ctx context.Context, arg UpsertEntitySourcesParams) error
	UpsertProjectEntities(ctx context.Context, arg UpsertProjectEntitiesParams) ([]UpsertProjectEntitiesRow, error)
	UpsertProjectRelationships(ctx context.Context, arg UpsertProjectRelationshipsParams) ([]UpsertProjectRelationshipsRow, error)
	UpsertRelationshipSources(ctx context.Context, arg UpsertRelationshipSourcesParams) error
	UpsertTextUnits(ctx context.Context, arg UpsertTextUnitsParams) ([]int64, error)
}

var _ Querier = (*Queries)(nil)
