// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteProjectRelationshipsByIDs = `-- name: DeleteProjectRelationshipsByIDs :exec
DELETE FROM relationships
WHERE project_id = $1
  AND id = ANY($2::text[])
`

type DeleteProjectRelationshipsByIDsParams struct {
	ProjectID string   `json:"project_id"`
	Ids       []string `json:"ids"`
}

func (q *Queries) DeleteProjectRelationshipsByIDs(ctx context.Context, arg DeleteProjectRelationshipsByIDsParams) error {
	_, err := q.db.Exec(ctx, deleteProjectRelationshipsByIDs, arg.ProjectID, arg.Ids)
	return err
}

const deleteRelationshipsWithoutSources = `-- name: DeleteRelationshipsWithoutSources :exec
DELETE FROM relationships 
WHERE project_id = $1 
  AND id NOT IN (SELECT DISTINCT relationship_id FROM relationship_sources)
`

func (q *Queries) DeleteRelationshipsWithoutSources(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteRelationshipsWithoutSources, projectID)
	return err
}

const getProjectRelationships = `-- name: GetProjectRelationships :many
SELECT r.id, r.source_id, r.target_id, r.description, r.rank FROM relationships r WHERE r.project_id = $1
`

type GetProjectRelationshipsRow struct {
	ID          string  `json:"id"`
	SourceID    string  `json:"source_id"`
	TargetID    string  `json:"target_id"`
	Description string  `json:"description"`
	Rank        float64 `json:"rank"`
}

func (q *Queries) GetProjectRelationships(ctx context.Context, projectID string) ([]GetProjectRelationshipsRow, error) {
	rows, err := q.db.Query(ctx, getProjectRelationships, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectRelationshipsRow{}
	for rows.Next() {
		var i GetProjectRelationshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Description,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectRelationshipsWithEntityNamesByIDs = `-- name: GetProjectRelationshipsWithEntityNamesByIDs :many
SELECT r.id, r.source_id, r.target_id, r.description, r.rank,
       se.name AS source_name,
       te.name AS target_name
FROM relationships r
JOIN entities se ON r.source_id = se.id
JOIN entities te ON r.target_id = te.id
WHERE r.id = ANY($1::text[])
`

type GetProjectRelationshipsWithEntityNamesByIDsRow struct {
	ID          string  `json:"id"`
	SourceID    string  `json:"source_id"`
	TargetID    string  `json:"target_id"`
	Description string  `json:"description"`
	Rank        float64 `json:"rank"`
	SourceName  string  `json:"source_name"`
	TargetName  string  `json:"target_name"`
}

func (q *Queries) GetProjectRelationshipsWithEntityNamesByIDs(ctx context.Context, ids []string) ([]GetProjectRelationshipsWithEntityNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProjectRelationshipsWithEntityNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectRelationshipsWithEntityNamesByIDsRow{}
	for rows.Next() {
		var i GetProjectRelationshipsWithEntityNamesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Description,
			&i.Rank,
			&i.SourceName,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationshipSourceCountsByIDs = `-- name: GetRelationshipSourceCountsByIDs :many
SELECT r.id, COUNT(rs.id)::int AS source_count
FROM relationships r
LEFT JOIN relationship_sources rs ON rs.relationship_id = r.id
WHERE r.id = ANY($1::text[])
  AND r.project_id = $2
GROUP BY r.id
`

type GetRelationshipSourceCountsByIDsParams struct {
	Column1   []string `json:"column_1"`
	ProjectID string   `json:"project_id"`
}

type GetRelationshipSourceCountsByIDsRow struct {
	ID          string `json:"id"`
	SourceCount int32  `json:"source_count"`
}

func (q *Queries) GetRelationshipSourceCountsByIDs(ctx context.Context, arg GetRelationshipSourceCountsByIDsParams) ([]GetRelationshipSourceCountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getRelationshipSourceCountsByIDs, arg.Column1, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRelationshipSourceCountsByIDsRow{}
	for rows.Next() {
		var i GetRelationshipSourceCountsByIDsRow
		if err := rows.Scan(&i.ID, &i.SourceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationshipSourceDescriptionsBatch = `-- name: GetRelationshipSourceDescriptionsBatch :many
SELECT rs.id, rs.created_at, rs.description
FROM relationship_sources rs
WHERE rs.relationship_id = $1
  AND (
      rs.created_at > $2
      OR (rs.created_at = $2 AND rs.id > $3)
  )
ORDER BY rs.created_at, rs.id
LIMIT $4
`

type GetRelationshipSourceDescriptionsBatchParams struct {
	RelationshipID  string             `json:"relationship_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	BatchLimit      int32              `json:"batch_limit"`
}

type GetRelationshipSourceDescriptionsBatchRow struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description string             `json:"description"`
}

func (q *Queries) GetRelationshipSourceDescriptionsBatch(ctx context.Context, arg GetRelationshipSourceDescriptionsBatchParams) ([]GetRelationshipSourceDescriptionsBatchRow, error) {
	rows, err := q.db.Query(ctx, getRelationshipSourceDescriptionsBatch,
		arg.RelationshipID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRelationshipSourceDescriptionsBatchRow{}
	for rows.Next() {
		var i GetRelationshipSourceDescriptionsBatchRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationshipSourceDescriptionsForFilesBatch = `-- name: GetRelationshipSourceDescriptionsForFilesBatch :many
SELECT rs.id, rs.created_at, rs.description
FROM relationship_sources rs
JOIN text_units tu ON tu.id = rs.text_unit_id
WHERE rs.relationship_id = $1
  AND tu.project_file_id = ANY($2::text[])
  AND (
      rs.created_at > $3
      OR (rs.created_at = $3 AND rs.id > $4)
  )
ORDER BY rs.created_at, rs.id
LIMIT $5
`

type GetRelationshipSourceDescriptionsForFilesBatchParams struct {
	RelationshipID  string             `json:"relationship_id"`
	FileIds         []string           `json:"file_ids"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	BatchLimit      int32              `json:"batch_limit"`
}

type GetRelationshipSourceDescriptionsForFilesBatchRow struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description string             `json:"description"`
}

func (q *Queries) GetRelationshipSourceDescriptionsForFilesBatch(ctx context.Context, arg GetRelationshipSourceDescriptionsForFilesBatchParams) ([]GetRelationshipSourceDescriptionsForFilesBatchRow, error) {
	rows, err := q.db.Query(ctx, getRelationshipSourceDescriptionsForFilesBatch,
		arg.RelationshipID,
		arg.FileIds,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRelationshipSourceDescriptionsForFilesBatchRow{}
	for rows.Next() {
		var i GetRelationshipSourceDescriptionsForFilesBatchRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationshipsWithSourcesFromFiles = `-- name: GetRelationshipsWithSourcesFromFiles :many
SELECT DISTINCT r.id, r.source_id, r.target_id, r.description, r.rank
FROM relationships r
JOIN relationship_sources rs ON rs.relationship_id = r.id
JOIN text_units tu ON tu.id = rs.text_unit_id
WHERE tu.project_file_id = ANY($1::text[])
  AND r.project_id = $2
`

type GetRelationshipsWithSourcesFromFilesParams struct {
	Column1   []string `json:"column_1"`
	ProjectID string   `json:"project_id"`
}

type GetRelationshipsWithSourcesFromFilesRow struct {
	ID          string  `json:"id"`
	SourceID    string  `json:"source_id"`
	TargetID    string  `json:"target_id"`
	Description string  `json:"description"`
	Rank        float64 `json:"rank"`
}

func (q *Queries) GetRelationshipsWithSourcesFromFiles(ctx context.Context, arg GetRelationshipsWithSourcesFromFilesParams) ([]GetRelationshipsWithSourcesFromFilesRow, error) {
	rows, err := q.db.Query(ctx, getRelationshipsWithSourcesFromFiles, arg.Column1, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRelationshipsWithSourcesFromFilesRow{}
	for rows.Next() {
		var i GetRelationshipsWithSourcesFromFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Description,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationshipsWithSourcesFromUnits = `-- name: GetRelationshipsWithSourcesFromUnits :many
SELECT DISTINCT r.id, r.source_id, r.target_id, r.description, r.rank
FROM relationships r
JOIN relationship_sources rs ON rs.relationship_id = r.id
WHERE rs.text_unit_id = ANY($1::text[])
  AND r.project_id = $2
`

type GetRelationshipsWithSourcesFromUnitsParams struct {
	Column1   []string `json:"column_1"`
	ProjectID string   `json:"project_id"`
}

type GetRelationshipsWithSourcesFromUnitsRow struct {
	ID          string  `json:"id"`
	SourceID    string  `json:"source_id"`
	TargetID    string  `json:"target_id"`
	Description string  `json:"description"`
	Rank        float64 `json:"rank"`
}

func (q *Queries) GetRelationshipsWithSourcesFromUnits(ctx context.Context, arg GetRelationshipsWithSourcesFromUnitsParams) ([]GetRelationshipsWithSourcesFromUnitsRow, error) {
	rows, err := q.db.Query(ctx, getRelationshipsWithSourcesFromUnits, arg.Column1, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRelationshipsWithSourcesFromUnitsRow{}
	for rows.Next() {
		var i GetRelationshipsWithSourcesFromUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Description,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferRelationshipSourcesBatchByMappings = `-- name: TransferRelationshipSourcesBatchByMappings :exec
WITH input AS (
    SELECT
        rel.relationship_id,
        ($2::text[])[rel.ord]::text AS canonical_id
    FROM unnest($3::text[]) WITH ORDINALITY AS rel(relationship_id, ord)
)
UPDATE relationship_sources rs
SET relationship_id = input.canonical_id
FROM input
JOIN relationships r ON r.id = input.relationship_id
WHERE rs.relationship_id = input.relationship_id
  AND r.project_id = $1
`

type TransferRelationshipSourcesBatchByMappingsParams struct {
	ProjectID       string   `json:"project_id"`
	CanonicalIds    []string `json:"canonical_ids"`
	RelationshipIds []string `json:"relationship_ids"`
}

func (q *Queries) TransferRelationshipSourcesBatchByMappings(ctx context.Context, arg TransferRelationshipSourcesBatchByMappingsParams) error {
	_, err := q.db.Exec(ctx, transferRelationshipSourcesBatchByMappings, arg.ProjectID, arg.CanonicalIds, arg.RelationshipIds)
	return err
}

const updateProjectRelationship = `-- name: UpdateProjectRelationship :one
UPDATE relationships SET description = $2, rank = $3, embedding = $4, updated_at = NOW() WHERE id = $1 RETURNING id
`

type UpdateProjectRelationshipParams struct {
	ID          string          `json:"id"`
	Description string          `json:"description"`
	Rank        float64         `json:"rank"`
	Embedding   pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateProjectRelationship(ctx context.Context, arg UpdateProjectRelationshipParams) (string, error) {
	row := q.db.QueryRow(ctx, updateProjectRelationship,
		arg.ID,
		arg.Description,
		arg.Rank,
		arg.Embedding,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateProjectRelationshipRanksByIDs = `-- name: UpdateProjectRelationshipRanksByIDs :exec
WITH input AS (
    SELECT
        rel.id,
        ($2::float8[])[rel.ord]::float8 AS rank
    FROM unnest($3::text[]) WITH ORDINALITY AS rel(id, ord)
)
UPDATE relationships r
SET rank = input.rank,
    updated_at = NOW()
FROM input
WHERE r.id = input.id
  AND r.project_id = $1
`

type UpdateProjectRelationshipRanksByIDsParams struct {
	ProjectID string    `json:"project_id"`
	Ranks     []float64 `json:"ranks"`
	Ids       []string  `json:"ids"`
}

func (q *Queries) UpdateProjectRelationshipRanksByIDs(ctx context.Context, arg UpdateProjectRelationshipRanksByIDsParams) error {
	_, err := q.db.Exec(ctx, updateProjectRelationshipRanksByIDs, arg.ProjectID, arg.Ranks, arg.Ids)
	return err
}

const updateProjectRelationshipsByIDs = `-- name: UpdateProjectRelationshipsByIDs :exec
WITH input AS (
    SELECT
        u.id,
        ($1::text[])[u.ord]::text AS description,
        ($2::vector[])[u.ord]::vector AS embedding
    FROM unnest($3::text[]) WITH ORDINALITY AS u(id, ord)
)
UPDATE relationships r
SET description = input.description,
    embedding = input.embedding,
    updated_at = NOW()
FROM input
WHERE r.id = input.id
`

type UpdateProjectRelationshipsByIDsParams struct {
	Descriptions []string          `json:"descriptions"`
	Embeddings   []pgvector.Vector `json:"embeddings"`
	Ids          []string          `json:"ids"`
}

func (q *Queries) UpdateProjectRelationshipsByIDs(ctx context.Context, arg UpdateProjectRelationshipsByIDsParams) error {
	_, err := q.db.Exec(ctx, updateProjectRelationshipsByIDs, arg.Descriptions, arg.Embeddings, arg.Ids)
	return err
}

const updateRelationshipSourceEntitiesBatch = `-- name: UpdateRelationshipSourceEntitiesBatch :exec
UPDATE relationships
SET source_id = $1
WHERE project_id = $2
  AND source_id = ANY($3::text[])
`

type UpdateRelationshipSourceEntitiesBatchParams struct {
	CanonicalID string   `json:"canonical_id"`
	ProjectID   string   `json:"project_id"`
	EntityIds   []string `json:"entity_ids"`
}

func (q *Queries) UpdateRelationshipSourceEntitiesBatch(ctx context.Context, arg UpdateRelationshipSourceEntitiesBatchParams) error {
	_, err := q.db.Exec(ctx, updateRelationshipSourceEntitiesBatch, arg.CanonicalID, arg.ProjectID, arg.EntityIds)
	return err
}

const updateRelationshipTargetEntitiesBatch = `-- name: UpdateRelationshipTargetEntitiesBatch :exec
UPDATE relationships
SET target_id = $1
WHERE project_id = $2
  AND target_id = ANY($3::text[])
`

type UpdateRelationshipTargetEntitiesBatchParams struct {
	CanonicalID string   `json:"canonical_id"`
	ProjectID   string   `json:"project_id"`
	EntityIds   []string `json:"entity_ids"`
}

func (q *Queries) UpdateRelationshipTargetEntitiesBatch(ctx context.Context, arg UpdateRelationshipTargetEntitiesBatchParams) error {
	_, err := q.db.Exec(ctx, updateRelationshipTargetEntitiesBatch, arg.CanonicalID, arg.ProjectID, arg.EntityIds)
	return err
}

const upsertProjectRelationships = `-- name: UpsertProjectRelationships :many
WITH input AS (
    SELECT
        u.id,
        ($2::text[])[u.ord]::text AS source_id,
        ($3::text[])[u.ord]::text AS target_id,
        ($4::float8[])[u.ord]::float8 AS rank,
        ($5::text[])[u.ord]::text AS description,
        ($6::vector[])[u.ord]::vector AS embedding
    FROM unnest($7::text[]) WITH ORDINALITY AS u(id, ord)
)
INSERT INTO relationships (id, project_id, source_id, target_id, rank, description, embedding)
SELECT id, $1::text, source_id, target_id, rank, description, embedding
FROM input
ON CONFLICT (id) DO UPDATE
SET project_id = EXCLUDED.project_id,
    source_id = EXCLUDED.source_id,
    target_id = EXCLUDED.target_id,
    rank = EXCLUDED.rank,
    description = EXCLUDED.description,
    embedding = EXCLUDED.embedding,
    updated_at = NOW()
RETURNING id
`

type UpsertProjectRelationshipsParams struct {
	ProjectID    string            `json:"project_id"`
	SourceIds    []string          `json:"source_ids"`
	TargetIds    []string          `json:"target_ids"`
	Ranks        []float64         `json:"ranks"`
	Descriptions []string          `json:"descriptions"`
	Embeddings   []pgvector.Vector `json:"embeddings"`
	Ids          []string          `json:"ids"`
}

func (q *Queries) UpsertProjectRelationships(ctx context.Context, arg UpsertProjectRelationshipsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, upsertProjectRelationships,
		arg.ProjectID,
		arg.SourceIds,
		arg.TargetIds,
		arg.Ranks,
		arg.Descriptions,
		arg.Embeddings,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelationshipSources = `-- name: UpsertRelationshipSources :exec
WITH input AS (
    SELECT
        u.id,
        ($1::text[])[u.ord]::text AS relationship_id,
        ($2::text[])[u.ord]::text AS text_unit_id,
        ($3::text[])[u.ord]::text AS description,
        ($4::vector[])[u.ord]::vector AS embedding
    FROM unnest($5::text[]) WITH ORDINALITY AS u(id, ord)
)
INSERT INTO relationship_sources (id, relationship_id, text_unit_id, description, embedding)
SELECT id, relationship_id, text_unit_id, description, embedding
FROM input
ON CONFLICT (id) DO UPDATE
SET relationship_id = EXCLUDED.relationship_id,
    text_unit_id = EXCLUDED.text_unit_id,
    description = EXCLUDED.description,
    embedding = EXCLUDED.embedding,
    updated_at = NOW()
`

type UpsertRelationshipSourcesParams struct {
	RelationshipIds []string          `json:"relationship_ids"`
	TextUnitIds     []string          `json:"text_unit_ids"`
	Descriptions    []string          `json:"descriptions"`
	Embeddings      []pgvector.Vector `json:"embeddings"`
	Ids             []string          `json:"ids"`
}

func (q *Queries) UpsertRelationshipSources(ctx context.Context, arg UpsertRelationshipSourcesParams) error {
	_, err := q.db.Exec(ctx, upsertRelationshipSources,
		arg.RelationshipIds,
		arg.TextUnitIds,
		arg.Descriptions,
		arg.Embeddings,
		arg.Ids,
	)
	return err
}
