// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staging.sql

package pgdb

import (
	"context"
)

const deleteStagedData = `-- name: DeleteStagedData :exec
DELETE FROM extraction_staging
WHERE correlation_id = $1 AND batch_id = $2
`

type DeleteStagedDataParams struct {
	CorrelationID string `json:"correlation_id"`
	BatchID       int32  `json:"batch_id"`
}

func (q *Queries) DeleteStagedData(ctx context.Context, arg DeleteStagedDataParams) error {
	_, err := q.db.Exec(ctx, deleteStagedData, arg.CorrelationID, arg.BatchID)
	return err
}

const getStagedEntities = `-- name: GetStagedEntities :many
SELECT data
FROM extraction_staging
WHERE correlation_id = $1 AND batch_id = $2 AND data_type = 'entity'
ORDER BY id
`

type GetStagedEntitiesParams struct {
	CorrelationID string `json:"correlation_id"`
	BatchID       int32  `json:"batch_id"`
}

func (q *Queries) GetStagedEntities(ctx context.Context, arg GetStagedEntitiesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getStagedEntities, arg.CorrelationID, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStagedRelationships = `-- name: GetStagedRelationships :many
SELECT data
FROM extraction_staging
WHERE correlation_id = $1 AND batch_id = $2 AND data_type = 'relationship'
ORDER BY id
`

type GetStagedRelationshipsParams struct {
	CorrelationID string `json:"correlation_id"`
	BatchID       int32  `json:"batch_id"`
}

func (q *Queries) GetStagedRelationships(ctx context.Context, arg GetStagedRelationshipsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getStagedRelationships, arg.CorrelationID, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStagedUnits = `-- name: GetStagedUnits :many
SELECT data
FROM extraction_staging
WHERE correlation_id = $1 AND batch_id = $2 AND data_type = 'unit'
ORDER BY id
`

type GetStagedUnitsParams struct {
	CorrelationID string `json:"correlation_id"`
	BatchID       int32  `json:"batch_id"`
}

func (q *Queries) GetStagedUnits(ctx context.Context, arg GetStagedUnitsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getStagedUnits, arg.CorrelationID, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStagedData = `-- name: InsertStagedData :exec
INSERT INTO extraction_staging (correlation_id, batch_id, project_id, data_type, data)
VALUES ($1, $2, $3, $4, $5)
`

type InsertStagedDataParams struct {
	CorrelationID string `json:"correlation_id"`
	BatchID       int32  `json:"batch_id"`
	ProjectID     int64  `json:"project_id"`
	DataType      string `json:"data_type"`
	Data          []byte `json:"data"`
}

func (q *Queries) InsertStagedData(ctx context.Context, arg InsertStagedDataParams) error {
	_, err := q.db.Exec(ctx, insertStagedData,
		arg.CorrelationID,
		arg.BatchID,
		arg.ProjectID,
		arg.DataType,
		arg.Data,
	)
	return err
}
