// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package pgdb

import (
	"context"
)

const addProcessTime = `-- name: AddProcessTime :exec
INSERT INTO stats 
    (project_id, amount, duration, stat_type)
VALUES
    ($1, $2, $3, $4)
`

type AddProcessTimeParams struct {
	ProjectID int64  `json:"project_id"`
	Amount    int32  `json:"amount"`
	Duration  int64  `json:"duration"`
	StatType  string `json:"stat_type"`
}

func (q *Queries) AddProcessTime(ctx context.Context, arg AddProcessTimeParams) error {
	_, err := q.db.Exec(ctx, addProcessTime,
		arg.ProjectID,
		arg.Amount,
		arg.Duration,
		arg.StatType,
	)
	return err
}

const predictProjectProcessTime = `-- name: PredictProjectProcessTime :one
SELECT (
    (SUM(duration)::DOUBLE PRECISION / NULLIF(SUM(amount), 0)) * $1
)::BIGINT AS predicted_duration
FROM stats
WHERE stat_type = $2
`

type PredictProjectProcessTimeParams struct {
	Duration int64  `json:"duration"`
	StatType string `json:"stat_type"`
}

func (q *Queries) PredictProjectProcessTime(ctx context.Context, arg PredictProjectProcessTimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, predictProjectProcessTime, arg.Duration, arg.StatType)
	var predicted_duration int64
	err := row.Scan(&predicted_duration)
	return predicted_duration, err
}
