// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: text_units.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTextUnitsByFileIDs = `-- name: DeleteTextUnitsByFileIDs :exec
DELETE FROM text_units WHERE project_file_id = ANY($1::text[])
`

func (q *Queries) DeleteTextUnitsByFileIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteTextUnitsByFileIDs, dollar_1)
	return err
}

const getFilesFromTextUnitIDs = `-- name: GetFilesFromTextUnitIDs :many
WITH project_scope AS (
  SELECT $1::text AS project_id
),
input_ids AS (
  SELECT DISTINCT trim(u.pid) AS pid
  FROM unnest($2::text[]) AS u(pid)
  WHERE trim(u.pid) <> ''
),
project_files_scope AS (
  SELECT pf.id
  FROM project_files pf
  JOIN project_scope ps ON ps.project_id = pf.project_id
),
resolved_text_units AS (
  SELECT tu.id, tu.project_file_id
  FROM input_ids i
  JOIN text_units tu ON tu.id = i.pid
  JOIN project_files_scope pfs ON pfs.id = tu.project_file_id
)
SELECT DISTINCT f.name, f.file_key, rtu.id
FROM resolved_text_units rtu
JOIN project_files f ON f.id = rtu.project_file_id
JOIN project_scope ps ON ps.project_id = f.project_id
`

type GetFilesFromTextUnitIDsParams struct {
	ProjectID string   `json:"project_id"`
	SourceIds []string `json:"source_ids"`
}

type GetFilesFromTextUnitIDsRow struct {
	Name    string `json:"name"`
	FileKey string `json:"file_key"`
	ID      string `json:"id"`
}

// Intentionally resolves only direct text_units.id values.
// Legacy entity_sources/relationship_sources fallback was removed on purpose.
func (q *Queries) GetFilesFromTextUnitIDs(ctx context.Context, arg GetFilesFromTextUnitIDsParams) ([]GetFilesFromTextUnitIDsRow, error) {
	rows, err := q.db.Query(ctx, getFilesFromTextUnitIDs, arg.ProjectID, arg.SourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFilesFromTextUnitIDsRow{}
	for rows.Next() {
		var i GetFilesFromTextUnitIDsRow
		if err := rows.Scan(&i.Name, &i.FileKey, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesWithMetadataFromTextUnitIDs = `-- name: GetFilesWithMetadataFromTextUnitIDs :many
WITH project_scope AS (
    SELECT $1::text AS project_id
),
project_files_scope AS (
    SELECT pf.id
    FROM project_files pf
    JOIN project_scope ps ON ps.project_id = pf.project_id
),
input_ids AS (
    SELECT DISTINCT trim(u.pid) AS pid
    FROM unnest($2::text[]) AS u(pid)
    WHERE trim(u.pid) <> ''
),
resolved_text_units AS (
    SELECT tu.id, tu.project_file_id
    FROM input_ids i
    JOIN text_units tu ON tu.id = i.pid
    JOIN project_files_scope pfs ON pfs.id = tu.project_file_id
)
SELECT DISTINCT f.name, f.file_key, f.metadata, rtu.id
FROM resolved_text_units rtu
JOIN project_files f ON f.id = rtu.project_file_id
JOIN project_scope ps ON ps.project_id = f.project_id
`

type GetFilesWithMetadataFromTextUnitIDsParams struct {
	ProjectID string   `json:"project_id"`
	SourceIds []string `json:"source_ids"`
}

type GetFilesWithMetadataFromTextUnitIDsRow struct {
	Name     string      `json:"name"`
	FileKey  string      `json:"file_key"`
	Metadata pgtype.Text `json:"metadata"`
	ID       string      `json:"id"`
}

// Intentionally resolves only direct text_units.id values.
// Legacy entity_sources/relationship_sources fallback was removed on purpose.
func (q *Queries) GetFilesWithMetadataFromTextUnitIDs(ctx context.Context, arg GetFilesWithMetadataFromTextUnitIDsParams) ([]GetFilesWithMetadataFromTextUnitIDsRow, error) {
	rows, err := q.db.Query(ctx, getFilesWithMetadataFromTextUnitIDs, arg.ProjectID, arg.SourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFilesWithMetadataFromTextUnitIDsRow{}
	for rows.Next() {
		var i GetFilesWithMetadataFromTextUnitIDsRow
		if err := rows.Scan(
			&i.Name,
			&i.FileKey,
			&i.Metadata,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectIDFromTextUnit = `-- name: GetProjectIDFromTextUnit :one
SELECT p.id FROM graphs p
JOIN project_files f ON f.project_id = p.id
JOIN text_units tu ON tu.project_file_id = f.id
WHERE tu.id = $1
`

func (q *Queries) GetProjectIDFromTextUnit(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getProjectIDFromTextUnit, id)
	err := row.Scan(&id)
	return id, err
}

const getTextUnitByID = `-- name: GetTextUnitByID :one
SELECT id, project_file_id, text, created_at, updated_at FROM text_units
WHERE id = $1
`

func (q *Queries) GetTextUnitByID(ctx context.Context, id string) (TextUnit, error) {
	row := q.db.QueryRow(ctx, getTextUnitByID, id)
	var i TextUnit
	err := row.Scan(
		&i.ID,
		&i.ProjectFileID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTextUnitIdsForFiles = `-- name: GetTextUnitIdsForFiles :many
SELECT id FROM text_units WHERE project_file_id = ANY($1::text[])
`

func (q *Queries) GetTextUnitIdsForFiles(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getTextUnitIdsForFiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTextUnits = `-- name: UpsertTextUnits :many
WITH input AS (
    SELECT
        u.id,
        ($1::text[])[u.ord]::text AS project_file_id,
        ($2::text[])[u.ord]::text AS text
    FROM unnest($3::text[]) WITH ORDINALITY AS u(id, ord)
)
INSERT INTO text_units (id, project_file_id, text)
SELECT id, project_file_id, text
FROM input
ON CONFLICT (id) DO UPDATE
SET project_file_id = EXCLUDED.project_file_id,
    text = EXCLUDED.text,
    updated_at = NOW()
RETURNING id
`

type UpsertTextUnitsParams struct {
	ProjectFileIds []string `json:"project_file_ids"`
	Texts          []string `json:"texts"`
	Ids            []string `json:"ids"`
}

func (q *Queries) UpsertTextUnits(ctx context.Context, arg UpsertTextUnitsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, upsertTextUnits, arg.ProjectFileIds, arg.Texts, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
