// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWorkflowRun = `-- name: CancelWorkflowRun :execrows
UPDATE workflow_runs
SET status = 'canceled',
    error_message = '',
    worker_id = '',
    lease_token = '',
    wait_reason = '',
    sleep_until = NULL,
    available_at = NOW(),
    updated_at = NOW(),
    last_heartbeat_at = NOW()
WHERE id = $1
  AND status IN ('pending', 'running')
`

func (q *Queries) CancelWorkflowRun(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelWorkflowRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelWorkflowRunsByProject = `-- name: CancelWorkflowRunsByProject :execrows
UPDATE workflow_runs
SET status = 'canceled',
    error_message = '',
    worker_id = '',
    lease_token = '',
    wait_reason = '',
    sleep_until = NULL,
    available_at = NOW(),
    updated_at = NOW(),
    last_heartbeat_at = NOW()
WHERE status IN ('pending', 'running')
  AND COALESCE(input->>'project_id', '') = $1::text
`

func (q *Queries) CancelWorkflowRunsByProject(ctx context.Context, projectID string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelWorkflowRunsByProject, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNextWorkflowRun = `-- name: ClaimNextWorkflowRun :one
WITH next_run AS (
    SELECT id
    FROM workflow_runs
    WHERE status IN ('pending', 'running')
      AND available_at <= NOW()
    ORDER BY available_at ASC, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE workflow_runs
SET status = 'running',
    worker_id = $1,
    lease_token = $3,
    available_at = $2,
    updated_at = NOW(),
    last_heartbeat_at = NOW(),
    attempt_count = CASE
        WHEN workflow_runs.status = 'pending'
            OR (workflow_runs.status = 'running' AND workflow_runs.wait_reason = '') THEN workflow_runs.attempt_count + 1
        ELSE workflow_runs.attempt_count
    END
FROM next_run
WHERE workflow_runs.id = next_run.id
RETURNING workflow_runs.id, workflow_runs.name, workflow_runs.version, workflow_runs.input, workflow_runs.output, workflow_runs.status, workflow_runs.error_message, workflow_runs.attempt_count, workflow_runs.available_at, workflow_runs.worker_id, workflow_runs.lease_token, workflow_runs.wait_reason, workflow_runs.sleep_until, workflow_runs.idempotency_key, workflow_runs.parent_run_id, workflow_runs.parent_step_name, workflow_runs.root_run_id, workflow_runs.retry_initial_interval_ms, workflow_runs.retry_backoff_coefficient, workflow_runs.retry_maximum_interval_ms, workflow_runs.retry_maximum_attempts, workflow_runs.created_at, workflow_runs.updated_at, workflow_runs.last_heartbeat_at
`

type ClaimNextWorkflowRunParams struct {
	WorkerID    string             `json:"worker_id"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LeaseToken  string             `json:"lease_token"`
}

func (q *Queries) ClaimNextWorkflowRun(ctx context.Context, arg ClaimNextWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, claimNextWorkflowRun, arg.WorkerID, arg.AvailableAt, arg.LeaseToken)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.WorkerID,
		&i.LeaseToken,
		&i.WaitReason,
		&i.SleepUntil,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.ParentStepName,
		&i.RootRunID,
		&i.RetryInitialIntervalMs,
		&i.RetryBackoffCoefficient,
		&i.RetryMaximumIntervalMs,
		&i.RetryMaximumAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const completeWorkflowRun = `-- name: CompleteWorkflowRun :execrows
UPDATE workflow_runs
SET output = $3,
    status = 'completed',
    error_message = '',
    worker_id = '',
    lease_token = '',
    wait_reason = '',
    sleep_until = NULL,
    available_at = NOW(),
    updated_at = NOW(),
    last_heartbeat_at = NOW()
WHERE id = $1
  AND worker_id = $2
  AND lease_token = $4
  AND status = 'running'
`

type CompleteWorkflowRunParams struct {
	ID         string `json:"id"`
	WorkerID   string `json:"worker_id"`
	Output     []byte `json:"output"`
	LeaseToken string `json:"lease_token"`
}

func (q *Queries) CompleteWorkflowRun(ctx context.Context, arg CompleteWorkflowRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeWorkflowRun,
		arg.ID,
		arg.WorkerID,
		arg.Output,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (
    id,
    name,
    version,
    input,
    available_at,
    idempotency_key,
    parent_run_id,
    parent_step_name,
    root_run_id,
    retry_initial_interval_ms,
    retry_backoff_coefficient,
    retry_maximum_interval_ms,
    retry_maximum_attempts
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (name, version, idempotency_key) DO UPDATE
SET updated_at = workflow_runs.updated_at
RETURNING id, name, version, input, output, status, error_message, attempt_count, available_at, worker_id, lease_token, wait_reason, sleep_until, idempotency_key, parent_run_id, parent_step_name, root_run_id, retry_initial_interval_ms, retry_backoff_coefficient, retry_maximum_interval_ms, retry_maximum_attempts, created_at, updated_at, last_heartbeat_at
`

type CreateWorkflowRunParams struct {
	ID                      string             `json:"id"`
	Name                    string             `json:"name"`
	Version                 string             `json:"version"`
	Input                   []byte             `json:"input"`
	AvailableAt             pgtype.Timestamptz `json:"available_at"`
	IdempotencyKey          pgtype.Text        `json:"idempotency_key"`
	ParentRunID             pgtype.Text        `json:"parent_run_id"`
	ParentStepName          pgtype.Text        `json:"parent_step_name"`
	RootRunID               pgtype.Text        `json:"root_run_id"`
	RetryInitialIntervalMs  int64              `json:"retry_initial_interval_ms"`
	RetryBackoffCoefficient float64            `json:"retry_backoff_coefficient"`
	RetryMaximumIntervalMs  int64              `json:"retry_maximum_interval_ms"`
	RetryMaximumAttempts    int32              `json:"retry_maximum_attempts"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Input,
		arg.AvailableAt,
		arg.IdempotencyKey,
		arg.ParentRunID,
		arg.ParentStepName,
		arg.RootRunID,
		arg.RetryInitialIntervalMs,
		arg.RetryBackoffCoefficient,
		arg.RetryMaximumIntervalMs,
		arg.RetryMaximumAttempts,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.WorkerID,
		&i.LeaseToken,
		&i.WaitReason,
		&i.SleepUntil,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.ParentStepName,
		&i.RootRunID,
		&i.RetryInitialIntervalMs,
		&i.RetryBackoffCoefficient,
		&i.RetryMaximumIntervalMs,
		&i.RetryMaximumAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const createWorkflowStepAttempt = `-- name: CreateWorkflowStepAttempt :one
INSERT INTO workflow_step_attempts (
    id,
    run_id,
    run_attempt,
    step_name,
    step_index,
    step_type,
    status,
    input,
    output,
    error_message,
    attempt_number,
    next_attempt_at,
    sleep_until,
    child_run_id,
    completed_at
) SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
WHERE EXISTS (
    SELECT 1
    FROM workflow_runs
    WHERE id = $2
      AND worker_id = $16
      AND lease_token = $17
      AND status = 'running'
)
RETURNING id, run_id, run_attempt, step_name, step_index, step_type, status, input, output, error_message, attempt_number, next_attempt_at, sleep_until, child_run_id, created_at, completed_at
`

type CreateWorkflowStepAttemptParams struct {
	ID            string             `json:"id"`
	RunID         string             `json:"run_id"`
	RunAttempt    int32              `json:"run_attempt"`
	StepName      string             `json:"step_name"`
	StepIndex     int32              `json:"step_index"`
	StepType      string             `json:"step_type"`
	Status        string             `json:"status"`
	Input         []byte             `json:"input"`
	Output        []byte             `json:"output"`
	ErrorMessage  string             `json:"error_message"`
	AttemptNumber int32              `json:"attempt_number"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	SleepUntil    pgtype.Timestamptz `json:"sleep_until"`
	ChildRunID    pgtype.Text        `json:"child_run_id"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	WorkerID      string             `json:"worker_id"`
	LeaseToken    string             `json:"lease_token"`
}

func (q *Queries) CreateWorkflowStepAttempt(ctx context.Context, arg CreateWorkflowStepAttemptParams) (WorkflowStepAttempt, error) {
	row := q.db.QueryRow(ctx, createWorkflowStepAttempt,
		arg.ID,
		arg.RunID,
		arg.RunAttempt,
		arg.StepName,
		arg.StepIndex,
		arg.StepType,
		arg.Status,
		arg.Input,
		arg.Output,
		arg.ErrorMessage,
		arg.AttemptNumber,
		arg.NextAttemptAt,
		arg.SleepUntil,
		arg.ChildRunID,
		arg.CompletedAt,
		arg.WorkerID,
		arg.LeaseToken,
	)
	var i WorkflowStepAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAttempt,
		&i.StepName,
		&i.StepIndex,
		&i.StepType,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.AttemptNumber,
		&i.NextAttemptAt,
		&i.SleepUntil,
		&i.ChildRunID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failWorkflowRun = `-- name: FailWorkflowRun :execrows
UPDATE workflow_runs
SET status = 'failed',
    error_message = $3,
    worker_id = '',
    lease_token = '',
    wait_reason = '',
    sleep_until = NULL,
    available_at = NOW(),
    updated_at = NOW(),
    last_heartbeat_at = NOW()
WHERE id = $1
  AND worker_id = $2
  AND lease_token = $4
`

type FailWorkflowRunParams struct {
	ID           string `json:"id"`
	WorkerID     string `json:"worker_id"`
	ErrorMessage string `json:"error_message"`
	LeaseToken   string `json:"lease_token"`
}

func (q *Queries) FailWorkflowRun(ctx context.Context, arg FailWorkflowRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, failWorkflowRun,
		arg.ID,
		arg.WorkerID,
		arg.ErrorMessage,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, name, version, input, output, status, error_message, attempt_count, available_at, worker_id, lease_token, wait_reason, sleep_until, idempotency_key, parent_run_id, parent_step_name, root_run_id, retry_initial_interval_ms, retry_backoff_coefficient, retry_maximum_interval_ms, retry_maximum_attempts, created_at, updated_at, last_heartbeat_at FROM workflow_runs
WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id string) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.WorkerID,
		&i.LeaseToken,
		&i.WaitReason,
		&i.SleepUntil,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.ParentStepName,
		&i.RootRunID,
		&i.RetryInitialIntervalMs,
		&i.RetryBackoffCoefficient,
		&i.RetryMaximumIntervalMs,
		&i.RetryMaximumAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const heartbeatWorkflowRun = `-- name: HeartbeatWorkflowRun :execrows
UPDATE workflow_runs
SET available_at = $3,
    updated_at = NOW(),
    last_heartbeat_at = NOW()
WHERE id = $1
  AND worker_id = $2
  AND lease_token = $4
  AND status = 'running'
`

type HeartbeatWorkflowRunParams struct {
	ID          string             `json:"id"`
	WorkerID    string             `json:"worker_id"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LeaseToken  string             `json:"lease_token"`
}

func (q *Queries) HeartbeatWorkflowRun(ctx context.Context, arg HeartbeatWorkflowRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatWorkflowRun,
		arg.ID,
		arg.WorkerID,
		arg.AvailableAt,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listWorkflowStepAttempts = `-- name: ListWorkflowStepAttempts :many
SELECT id, run_id, run_attempt, step_name, step_index, step_type, status, input, output, error_message, attempt_number, next_attempt_at, sleep_until, child_run_id, created_at, completed_at FROM workflow_step_attempts
WHERE run_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListWorkflowStepAttempts(ctx context.Context, runID string) ([]WorkflowStepAttempt, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepAttempts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowStepAttempt{}
	for rows.Next() {
		var i WorkflowStepAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RunAttempt,
			&i.StepName,
			&i.StepIndex,
			&i.StepType,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.ErrorMessage,
			&i.AttemptNumber,
			&i.NextAttemptAt,
			&i.SleepUntil,
			&i.ChildRunID,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleWorkflowRun = `-- name: RescheduleWorkflowRun :execrows
UPDATE workflow_runs
SET status = $3::text,
    error_message = $5,
    worker_id = '',
    lease_token = '',
    wait_reason = $6,
    sleep_until = $7,
    available_at = $4,
    updated_at = NOW(),
    last_heartbeat_at = NOW()
WHERE id = $1
  AND worker_id = $2
  AND lease_token = $8
`

type RescheduleWorkflowRunParams struct {
	ID           string             `json:"id"`
	WorkerID     string             `json:"worker_id"`
	Column3      string             `json:"column_3"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	ErrorMessage string             `json:"error_message"`
	WaitReason   string             `json:"wait_reason"`
	SleepUntil   pgtype.Timestamptz `json:"sleep_until"`
	LeaseToken   string             `json:"lease_token"`
}

func (q *Queries) RescheduleWorkflowRun(ctx context.Context, arg RescheduleWorkflowRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleWorkflowRun,
		arg.ID,
		arg.WorkerID,
		arg.Column3,
		arg.AvailableAt,
		arg.ErrorMessage,
		arg.WaitReason,
		arg.SleepUntil,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
