// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: process.sql

package db

import (
	"context"
)

const deleteProjectProcess = `-- name: DeleteProjectProcess :exec
DELETE FROM project_process 
WHERE project_id = $1
`

func (q *Queries) DeleteProjectProcess(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, deleteProjectProcess, projectID)
	return err
}

const getProjectProcess = `-- name: GetProjectProcess :one
SELECT 
    project_id,
    percentage,
    current_step,
    estimated_duration
FROM project_process 
WHERE project_id = $1
`

type GetProjectProcessRow struct {
	ProjectID         int64  `json:"project_id"`
	Percentage        int32  `json:"percentage"`
	CurrentStep       string `json:"current_step"`
	EstimatedDuration int64  `json:"estimated_duration"`
}

func (q *Queries) GetProjectProcess(ctx context.Context, projectID int64) (GetProjectProcessRow, error) {
	row := q.db.QueryRow(ctx, getProjectProcess, projectID)
	var i GetProjectProcessRow
	err := row.Scan(
		&i.ProjectID,
		&i.Percentage,
		&i.CurrentStep,
		&i.EstimatedDuration,
	)
	return i, err
}

const updateProjectProcessPercentage = `-- name: UpdateProjectProcessPercentage :exec
UPDATE project_process 
SET 
    percentage = $2,
    updated_at = NOW() 
WHERE project_id = $1
`

type UpdateProjectProcessPercentageParams struct {
	ProjectID  int64 `json:"project_id"`
	Percentage int32 `json:"percentage"`
}

func (q *Queries) UpdateProjectProcessPercentage(ctx context.Context, arg UpdateProjectProcessPercentageParams) error {
	_, err := q.db.Exec(ctx, updateProjectProcessPercentage, arg.ProjectID, arg.Percentage)
	return err
}

const updateProjectProcessStep = `-- name: UpdateProjectProcessStep :exec
UPDATE project_process 
SET 
    current_step = $2, 
    updated_at = NOW() 
WHERE project_id = $1
`

type UpdateProjectProcessStepParams struct {
	ProjectID   int64  `json:"project_id"`
	CurrentStep string `json:"current_step"`
}

func (q *Queries) UpdateProjectProcessStep(ctx context.Context, arg UpdateProjectProcessStepParams) error {
	_, err := q.db.Exec(ctx, updateProjectProcessStep, arg.ProjectID, arg.CurrentStep)
	return err
}

const updateProjectProcessStepAndPrediction = `-- name: UpdateProjectProcessStepAndPrediction :exec
UPDATE project_process 
SET 
    current_step = $2, 
    estimated_duration = $3,
    percentage = 0,
    updated_at = NOW() 
WHERE project_id = $1
`

type UpdateProjectProcessStepAndPredictionParams struct {
	ProjectID         int64  `json:"project_id"`
	CurrentStep       string `json:"current_step"`
	EstimatedDuration int64  `json:"estimated_duration"`
}

func (q *Queries) UpdateProjectProcessStepAndPrediction(ctx context.Context, arg UpdateProjectProcessStepAndPredictionParams) error {
	_, err := q.db.Exec(ctx, updateProjectProcessStepAndPrediction, arg.ProjectID, arg.CurrentStep, arg.EstimatedDuration)
	return err
}

const updateProjectProcessStepOnly = `-- name: UpdateProjectProcessStepOnly :exec
UPDATE project_process 
SET 
    current_step = $2
WHERE project_id = $1
`

type UpdateProjectProcessStepOnlyParams struct {
	ProjectID   int64  `json:"project_id"`
	CurrentStep string `json:"current_step"`
}

func (q *Queries) UpdateProjectProcessStepOnly(ctx context.Context, arg UpdateProjectProcessStepOnlyParams) error {
	_, err := q.db.Exec(ctx, updateProjectProcessStepOnly, arg.ProjectID, arg.CurrentStep)
	return err
}

const upsertProjectProcess = `-- name: UpsertProjectProcess :exec
INSERT INTO project_process (
    project_id,
    percentage,
    current_step,
    estimated_duration,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
)
ON CONFLICT (project_id) DO UPDATE SET
    percentage = EXCLUDED.percentage,
    current_step = EXCLUDED.current_step,
    estimated_duration = EXCLUDED.estimated_duration,
    updated_at = NOW()
`

type UpsertProjectProcessParams struct {
	ProjectID         int64  `json:"project_id"`
	Percentage        int32  `json:"percentage"`
	CurrentStep       string `json:"current_step"`
	EstimatedDuration int64  `json:"estimated_duration"`
}

func (q *Queries) UpsertProjectProcess(ctx context.Context, arg UpsertProjectProcessParams) error {
	_, err := q.db.Exec(ctx, upsertProjectProcess,
		arg.ProjectID,
		arg.Percentage,
		arg.CurrentStep,
		arg.EstimatedDuration,
	)
	return err
}
