// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddFileToProject(ctx context.Context, arg AddFileToProjectParams) (ProjectFile, error)
	AddProcessTime(ctx context.Context, arg AddProcessTimeParams) error
	AddProjectEntity(ctx context.Context, arg AddProjectEntityParams) (int64, error)
	AddProjectEntitySource(ctx context.Context, arg AddProjectEntitySourceParams) (int64, error)
	AddProjectFileTextUnit(ctx context.Context, arg AddProjectFileTextUnitParams) (int64, error)
	AddProjectRelationship(ctx context.Context, arg AddProjectRelationshipParams) (int64, error)
	AddProjectRelationshipSource(ctx context.Context, arg AddProjectRelationshipSourceParams) (int64, error)
	AddProjectUpdate(ctx context.Context, arg AddProjectUpdateParams) error
	AddTokenCountToFile(ctx context.Context, arg AddTokenCountToFileParams) error
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (GroupUser, error)
	CountEntitySources(ctx context.Context, entityID int64) (int32, error)
	CountEntitySourcesFromUnits(ctx context.Context, arg CountEntitySourcesFromUnitsParams) (int32, error)
	CountRelationshipSourcesFromUnits(ctx context.Context, arg CountRelationshipSourcesFromUnitsParams) (int32, error)
	CreateGroup(ctx context.Context, name string) (Group, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteEntitiesWithoutSources(ctx context.Context, projectID int64) error
	DeleteEntitySources(ctx context.Context, entityID int64) error
	DeleteFileFromProject(ctx context.Context, arg DeleteFileFromProjectParams) error
	DeleteGroup(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteProjectEntity(ctx context.Context, id int64) error
	DeleteProjectEntityByPublicID(ctx context.Context, publicID string) error
	DeleteProjectFile(ctx context.Context, id int64) error
	DeleteProjectProcess(ctx context.Context, projectID int64) error
	DeleteProjectRelationship(ctx context.Context, id int64) error
	DeleteProjectRelationshipByPublicID(ctx context.Context, publicID string) error
	DeleteRelationshipSources(ctx context.Context, relationshipID int64) error
	DeleteRelationshipsWithoutSources(ctx context.Context, projectID int64) error
	DeleteTextUnitsByFileIDs(ctx context.Context, dollar_1 []int64) error
	DeleteUserFromGroup(ctx context.Context, arg DeleteUserFromGroupParams) error
	FindDuplicateRelationships(ctx context.Context, projectID int64) ([]FindDuplicateRelationshipsRow, error)
	FindEntitiesWithSimilarNames(ctx context.Context, projectID int64) ([]FindEntitiesWithSimilarNamesRow, error)
	FindRelevantEntities(ctx context.Context, arg FindRelevantEntitiesParams) ([]FindRelevantEntitiesRow, error)
	FindRelevantEntitySources(ctx context.Context, arg FindRelevantEntitySourcesParams) ([]FindRelevantEntitySourcesRow, error)
	FindRelevantRelationSources(ctx context.Context, arg FindRelevantRelationSourcesParams) ([]FindRelevantRelationSourcesRow, error)
	FindRelevantSourcesForEntities(ctx context.Context, arg FindRelevantSourcesForEntitiesParams) ([]FindRelevantSourcesForEntitiesRow, error)
	FindRelevantSourcesForRelations(ctx context.Context, arg FindRelevantSourcesForRelationsParams) ([]FindRelevantSourcesForRelationsRow, error)
	FindSimilarEntities(ctx context.Context, arg FindSimilarEntitiesParams) ([]int64, error)
	FindSimilarEntitySources(ctx context.Context, arg FindSimilarEntitySourcesParams) ([]FindSimilarEntitySourcesRow, error)
	GetActiveProjectFiles(ctx context.Context, projectID int64) ([]ProjectFile, error)
	GetAllEntitySourceDescriptions(ctx context.Context, entityID int64) ([]GetAllEntitySourceDescriptionsRow, error)
	GetAllGroups(ctx context.Context) ([]GetAllGroupsRow, error)
	GetAllProjectsWithGroups(ctx context.Context) ([]GetAllProjectsWithGroupsRow, error)
	GetAllRelationshipSourceDescriptions(ctx context.Context, relationshipID int64) ([]GetAllRelationshipSourceDescriptionsRow, error)
	GetDeletedProjectFiles(ctx context.Context, projectID int64) ([]ProjectFile, error)
	GetEntitiesWithSourcesFromUnits(ctx context.Context, arg GetEntitiesWithSourcesFromUnitsParams) ([]GetEntitiesWithSourcesFromUnitsRow, error)
	GetEntityNeighbours(ctx context.Context, sourceID int64) ([]GetEntityNeighboursRow, error)
	GetEntityNeighboursRanked(ctx context.Context, arg GetEntityNeighboursRankedParams) ([]GetEntityNeighboursRankedRow, error)
	GetEntityTypes(ctx context.Context, projectID int64) ([]GetEntityTypesRow, error)
	GetFilesFromTextUnitIDs(ctx context.Context, dollar_1 []string) ([]GetFilesFromTextUnitIDsRow, error)
	GetFilesWithMetadataFromTextUnitIDs(ctx context.Context, dollar_1 []string) ([]GetFilesWithMetadataFromTextUnitIDsRow, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetGroupUsers(ctx context.Context, groupID int64) ([]GroupUser, error)
	GetGroups(ctx context.Context) ([]Group, error)
	GetGroupsForUser(ctx context.Context, userID int64) ([]GetGroupsForUserRow, error)
	GetMinProjectEntities(ctx context.Context, projectID int64) ([]GetMinProjectEntitiesRow, error)
	GetMinProjectRelationships(ctx context.Context, projectID int64) ([]GetMinProjectRelationshipsRow, error)
	GetProjectEntities(ctx context.Context, projectID int64) ([]GetProjectEntitiesRow, error)
	GetProjectEntitiesByIDs(ctx context.Context, dollar_1 []int64) ([]GetProjectEntitiesByIDsRow, error)
	GetProjectEntitiesByNames(ctx context.Context, arg GetProjectEntitiesByNamesParams) ([]GetProjectEntitiesByNamesRow, error)
	GetProjectEntityByID(ctx context.Context, id int64) (GetProjectEntityByIDRow, error)
	GetProjectEntityByName(ctx context.Context, arg GetProjectEntityByNameParams) (GetProjectEntityByNameRow, error)
	GetProjectEntityByNameSimilarity(ctx context.Context, arg GetProjectEntityByNameSimilarityParams) (GetProjectEntityByNameSimilarityRow, error)
	GetProjectEntityByPublicID(ctx context.Context, publicID string) (GetProjectEntityByPublicIDRow, error)
	GetProjectEntityNames(ctx context.Context, projectID int64) ([]string, error)
	GetProjectEntitySourcesByPublicID(ctx context.Context, publicID string) ([]GetProjectEntitySourcesByPublicIDRow, error)
	GetProjectEntityWithSourcesFromUnitID(ctx context.Context, textUnitID int64) ([]GetProjectEntityWithSourcesFromUnitIDRow, error)
	GetProjectFiles(ctx context.Context, projectID int64) ([]ProjectFile, error)
	GetProjectIDFromTextUnit(ctx context.Context, publicID string) (int64, error)
	GetProjectProcess(ctx context.Context, projectID int64) (GetProjectProcessRow, error)
	GetProjectRelationshipByEntityIDs(ctx context.Context, arg GetProjectRelationshipByEntityIDsParams) (GetProjectRelationshipByEntityIDsRow, error)
	GetProjectRelationshipByEntityNames(ctx context.Context, arg GetProjectRelationshipByEntityNamesParams) (GetProjectRelationshipByEntityNamesRow, error)
	GetProjectRelationshipByID(ctx context.Context, id int64) (GetProjectRelationshipByIDRow, error)
	GetProjectRelationshipByPublicID(ctx context.Context, publicID string) (GetProjectRelationshipByPublicIDRow, error)
	GetProjectRelationshipSourcesByPublicID(ctx context.Context, publicID string) ([]GetProjectRelationshipSourcesByPublicIDRow, error)
	GetProjectRelationshipWithSourcesFromUnitID(ctx context.Context, textUnitID int64) ([]GetProjectRelationshipWithSourcesFromUnitIDRow, error)
	GetProjectRelationships(ctx context.Context, projectID int64) ([]GetProjectRelationshipsRow, error)
	GetProjectRelationshipsByIDs(ctx context.Context, dollar_1 []int64) ([]GetProjectRelationshipsByIDsRow, error)
	GetProjectSystemPrompts(ctx context.Context, projectID int64) ([]ProjectSystemPrompt, error)
	GetProjects(ctx context.Context) ([]Project, error)
	GetProjectsByGroup(ctx context.Context, groupID int64) ([]Project, error)
	GetProjectsForUser(ctx context.Context, userID int64) ([]GetProjectsForUserRow, error)
	GetRelationshipsWithSourcesFromUnits(ctx context.Context, arg GetRelationshipsWithSourcesFromUnitsParams) ([]GetRelationshipsWithSourcesFromUnitsRow, error)
	GetTextUnitByPublicId(ctx context.Context, publicID string) (TextUnit, error)
	GetTextUnitIdsForFiles(ctx context.Context, dollar_1 []int64) ([]GetTextUnitIdsForFilesRow, error)
	GetTokenCountOfFile(ctx context.Context, id int64) (int32, error)
	GetUsers(ctx context.Context) ([]User, error)
	IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (int64, error)
	IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (int64, error)
	MarkProjectFileAsDeleted(ctx context.Context, arg MarkProjectFileAsDeletedParams) error
	PredictProjectProcessTime(ctx context.Context, arg PredictProjectProcessTimeParams) (int64, error)
	SearchEntitiesByEmbedding(ctx context.Context, arg SearchEntitiesByEmbeddingParams) ([]SearchEntitiesByEmbeddingRow, error)
	SearchEntitiesByType(ctx context.Context, arg SearchEntitiesByTypeParams) ([]SearchEntitiesByTypeRow, error)
	TransferEntitySources(ctx context.Context, arg TransferEntitySourcesParams) error
	TransferRelationshipSources(ctx context.Context, arg TransferRelationshipSourcesParams) error
	UpdateEntityName(ctx context.Context, arg UpdateEntityNameParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectEntity(ctx context.Context, arg UpdateProjectEntityParams) (int64, error)
	UpdateProjectEntityByID(ctx context.Context, arg UpdateProjectEntityByIDParams) (int64, error)
	UpdateProjectFileMetadata(ctx context.Context, arg UpdateProjectFileMetadataParams) error
	UpdateProjectProcessPercentage(ctx context.Context, arg UpdateProjectProcessPercentageParams) error
	UpdateProjectProcessStep(ctx context.Context, arg UpdateProjectProcessStepParams) error
	UpdateProjectProcessStepAndPrediction(ctx context.Context, arg UpdateProjectProcessStepAndPredictionParams) error
	UpdateProjectProcessStepOnly(ctx context.Context, arg UpdateProjectProcessStepOnlyParams) error
	UpdateProjectRelationship(ctx context.Context, arg UpdateProjectRelationshipParams) (int64, error)
	UpdateProjectRelationshipByID(ctx context.Context, arg UpdateProjectRelationshipByIDParams) (int64, error)
	UpdateProjectState(ctx context.Context, arg UpdateProjectStateParams) (Project, error)
	UpdateRelationshipRank(ctx context.Context, arg UpdateRelationshipRankParams) error
	UpdateRelationshipSourceEntity(ctx context.Context, arg UpdateRelationshipSourceEntityParams) error
	UpdateRelationshipTargetEntity(ctx context.Context, arg UpdateRelationshipTargetEntityParams) error
	UpsertProjectProcess(ctx context.Context, arg UpsertProjectProcessParams) error
}

var _ Querier = (*Queries)(nil)
